auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /loki
  replication_factor: 1

storage:
    s3:
      s3: null
      endpoint: http://minio:9000
      region: null
      secretAccessKey: XXXXXXXXXXX
      accessKeyId: XXXXXXXXXX
      s3ForcePathStyle: true
      insecure: true


schema_config:
  configs:
    - from: 2025-01-01  # Ensure you have a valid "from" date
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/tsdb-index  # ✅ Required for TSDB
    cache_location: /loki/tsdb-cache  # ✅ Required for caching
  aws:
    s3: http://minio:9000/
    bucketnames: logging
    access_key_id: ${MINIO_ROOT_USER}
    secret_access_key: ${MINIO_ROOT_PASSWORD}
    insecure: true

compactor:
  working_directory: /loki/tsdb-compactor  # ✅ Required for TSDB compactor

ruler:
  storage:
    type: s3
  rule_path: /loki/rules-temp