# Project information
site_name: Huybrechts.xyz
site_description: Documentation for Huybrechts.xyz
site_author: Vincent Huybrechts
site_url: https://huybrechts.xyz

# Navigation
nav:
    - Home: index.md
    - Local host: env/localhost.md
    - Docker host: env/dockerhost.md
    - Development: env/development.md
    - Staging: env/staging.md
    - Production: env/production.md
    - Traefik: svc/traefik.md
    - Consul: svc/consul.md
    - Vault: svc/vault.md
    - Elastic Stack: svc/elastic.md
    - ASP.NET Core: how/dotnet.md
    - Managing Secrets: how/secrets.md
   
# Repository
# repo_name: squidfunk/mkdocs-material
# repo_url: https://github.com/squidfunk/mkdocs-material

# Copyright
copyright: Copyright &copy; 2020 Vincent Huybrechts

# Configuration
theme:
    name: material
    language: en
    palette:
        primary: indigo
        accent: indigo
    font:
        text: Roboto
        code: Roboto Mono

# Extras
extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: https://linkedin.com/in/squidfunk

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true