//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huybrechts.Web.Pages.Features.Platform {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huybrechts.Web.Pages.Features.Platform.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Selection.
        /// </summary>
        public static string Add_Selection {
            get {
                return ResourceManager.GetString("Add Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string Clear_Filter {
            get {
                return ResourceManager.GetString("Clear Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new platform by entering its name, description, and supported automation provider. Use this page to configure a new cloud platform or on-premise solution..
        /// </summary>
        public static string CreateInfo {
            get {
                return ResourceManager.GetString("CreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create platform.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an existing platform from the system. Deleting a platform will also remove all associated regions, products, and services. Use this page to permanently delete a cloud platform or on-premise solution..
        /// </summary>
        public static string DeleteInfo {
            get {
                return ResourceManager.GetString("DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete platform.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify an existing platform by updating its name, description, or supported automation provider. Use this page to adjust the configuration of an existing cloud platform or on-premise solution..
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit platform.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importeer.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage cloud platforms and on-premise solutions, including the creation, editing, and deletion of platforms. Easily navigate to configure associated regions, products, and services..
        /// </summary>
        public static string IndexInfo {
            get {
                return ResourceManager.GetString("IndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage you cloud and on premise computer platforms.
        /// </summary>
        public static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new product to the platform by specifying its name, label, and category. Use this page to define a new service or resource type for a cloud platform or on-premise solution..
        /// </summary>
        public static string ProductCreateInfo {
            get {
                return ResourceManager.GetString("ProductCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product.
        /// </summary>
        public static string ProductCreateTitle {
            get {
                return ResourceManager.GetString("ProductCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an existing product from the platform. Deleting a product will permanently remove it from the list of available services and resources. Use this page to delete a product from a cloud platform or on-premise solution..
        /// </summary>
        public static string ProductDeleteInfo {
            get {
                return ResourceManager.GetString("ProductDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete product.
        /// </summary>
        public static string ProductDeleteTitle {
            get {
                return ResourceManager.GetString("ProductDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the details of an existing product, including its name, label, or category. Use this page to update the configuration of a service or resource type within a cloud platform or on-premise solution..
        /// </summary>
        public static string ProductEditInfo {
            get {
                return ResourceManager.GetString("ProductEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        public static string ProductEditTitle {
            get {
                return ResourceManager.GetString("ProductEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import products into the platform by selecting from the full list of available services and resources. Use this page to quickly add multiple products to a cloud platform or on-premise solution..
        /// </summary>
        public static string ProductImportInfo {
            get {
                return ResourceManager.GetString("ProductImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import products.
        /// </summary>
        public static string ProductImportTitle {
            get {
                return ResourceManager.GetString("ProductImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage the list of products available on the platform. Use this page to create, update, or delete services and resources offered by a cloud platform or on-premise solution..
        /// </summary>
        public static string ProductIndexInfo {
            get {
                return ResourceManager.GetString("ProductIndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string ProductIndexTitle {
            get {
                return ResourceManager.GetString("ProductIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new region to a platform by specifying its name, label, and description. Use this page to define a new data center region for a cloud platform or on-premise solution..
        /// </summary>
        public static string RegionCreateInfo {
            get {
                return ResourceManager.GetString("RegionCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create region.
        /// </summary>
        public static string RegionCreateTitle {
            get {
                return ResourceManager.GetString("RegionCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an existing region from a platform. Deleting a region will permanently remove the associated data center location. Use this page to delete a region from a cloud platform or on-premise solution..
        /// </summary>
        public static string RegionDeleteInfo {
            get {
                return ResourceManager.GetString("RegionDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete region.
        /// </summary>
        public static string RegionDeleteTitle {
            get {
                return ResourceManager.GetString("RegionDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the details of an existing region, including its name, label, or description. Use this page to update the configuration of a data center region within a cloud platform or on-premise solution..
        /// </summary>
        public static string RegionEditInfo {
            get {
                return ResourceManager.GetString("RegionEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit region.
        /// </summary>
        public static string RegionEditTitle {
            get {
                return ResourceManager.GetString("RegionEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import regions into the platform by selecting from the full list of available data center locations. Use this page to quickly add multiple regions to a cloud platform or on-premise solution..
        /// </summary>
        public static string RegionImportInfo {
            get {
                return ResourceManager.GetString("RegionImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import regions.
        /// </summary>
        public static string RegionImportTitle {
            get {
                return ResourceManager.GetString("RegionImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage the list of regions within a platform. Use this page to create, update, or delete data center regions associated with a cloud platform or on-premise solution..
        /// </summary>
        public static string RegionIndexInfo {
            get {
                return ResourceManager.GetString("RegionIndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string RegionIndexTitle {
            get {
                return ResourceManager.GetString("RegionIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search___ {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new service to the platform by specifying its name, label, and associated product. Use this page to define a new service, including its description, cost driver, and pricing details..
        /// </summary>
        public static string ServiceCreateInfo {
            get {
                return ResourceManager.GetString("ServiceCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create service.
        /// </summary>
        public static string ServiceCreateTitle {
            get {
                return ResourceManager.GetString("ServiceCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an existing service from the platform. Deleting a service will permanently remove it from the list of available offerings. Use this page to delete a service from a cloud platform or on-premise solution..
        /// </summary>
        public static string ServiceDeleteInfo {
            get {
                return ResourceManager.GetString("ServiceDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete service.
        /// </summary>
        public static string ServiceDeleteTitle {
            get {
                return ResourceManager.GetString("ServiceDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the details of an existing service, including its name, label, or description. Use this page to update information about a service, including its cost parameters and limitations..
        /// </summary>
        public static string ServiceEditInfo {
            get {
                return ResourceManager.GetString("ServiceEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit service.
        /// </summary>
        public static string ServiceEditTitle {
            get {
                return ResourceManager.GetString("ServiceEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import services into the platform by selecting from the full list of available services. This function will also create associated service rates and measurement units. Use this page to quickly add multiple services to a cloud platform or on-premise solution..
        /// </summary>
        public static string ServiceImportInfo {
            get {
                return ResourceManager.GetString("ServiceImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import services.
        /// </summary>
        public static string ServiceImportTitle {
            get {
                return ResourceManager.GetString("ServiceImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage the list of services offered by the platform. Use this page to create, update, or delete services provided by a cloud platform or on-premise solution..
        /// </summary>
        public static string ServiceIndexInfo {
            get {
                return ResourceManager.GetString("ServiceIndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string ServiceIndexTitle {
            get {
                return ResourceManager.GetString("ServiceIndexTitle", resourceCulture);
            }
        }
    }
}
