
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    secrets:
      - APP_ROOT_USERNAME
      - APP_ROOT_PASSWORD
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      ENVIRONMENT: ${ENVIRONMENT}
      KC_LOG: console #,file
      KC_LOG_LEVEL: INFO
      #KC_LOG_FILE: /home/keycloak.log
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HOSTNAME: https://iam.${DOMAIN_DEV}
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_METRICS_HISTOGRAMS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_TRACING_ENABLED: "true"
      KC_TRACING_PROPAGATORS: tracecontext,baggage
      KC_TRACING_SAMPLER: always_on
      KC_TRACING_ENDPOINT: http://telemetry:4317
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: xyzdb
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME_FILE: /run/secrets/APP_ROOT_USERNAME
      KC_DB_PASSWORD_FILE: /run/secrets/APP_ROOT_PASSWORD
      KC_BOOTSTRAP_ADMIN_USERNAME_FILE: /run/secrets/APP_ROOT_USERNAME
      KC_BOOTSTRAP_ADMIN_PASSWORD_FILE: /run/secrets/APP_ROOT_PASSWORD
    entrypoint: usr/local/bin/entrypoint.sh --proxy-headers forwarded --hostname-debug=true --features=opentelemetry #--import-realm
    volumes:
      - ${APP_PATH}/keycloak/keycloak-entry.sh:/usr/local/bin/entrypoint.sh
      #- ${APP_PATH}/keycloak/keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    networks:
      - public
    healthcheck:
      test: ["CMD", "bash", "-c", "[ $$(/opt/keycloak/bin/kcadm.sh get serverinfo --realm Keycloak --fields '*' --server http://localhost:8080/admin/serverinfo 2>&1 | grep Unauthorized | wc -l ) -eq 1 ]"]
      interval: 15s
      retries: 3
      timeout: 5s
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==${DOCKER_WORKER}
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
      labels:
        # Enable Traefik
        - traefik.enable=true
        - traefik.tags=${ENVIRONMENT}
        - traefik.http.services.keycloak.loadbalancer.server.scheme=http
        - traefik.http.services.keycloak.loadbalancer.server.port=8080
        - traefik.http.routers.keycloak.rule=Host(`iam.${DOMAIN_DEV}`)
        - traefik.http.routers.keycloak.entrypoints=websecure
        - traefik.http.routers.keycloak.tls.certresolver=${TRAEFIK_RESOLVER}
        - traefik.http.routers.keycloak.middlewares=${TRAEFIK_AUTH}


  website:
    image: huybrechts/website:${environment}
    secrets:
      - APP_ROOT_USERNAME
      - APP_ROOT_PASSWORD
      - APP_AUTH_GOOGLE
      - APP_SMTP_OPTIONS
      # - APP_HOST_EMAIL
      # - APP_DATA_URL
      # - APP_DATA_NAME
      # - APP_DATA_USERNAME
      # - APP_DATA_PASSWORD
      # - APP_AUTH_GOOGLE
      # - APP_SMTP_OPTIONS
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DOTNET_RUNNING_IN_CONTAINER: 1
      APP_ROOT_EMAIL: ${APP_ROOT_EMAIL}
      APP_AUTH_GOOGLE: /run/secrets/APP_AUTH_GOOGLE
      APP_SMTP_OPTIONS: /run/secrets/APP_SMTP_OPTIONS
      APP_DATA_NAME: "xyzdb"
      APP_DATA_USERNAME: /run/secrets/APP_ROOT_USERNAME
      APP_DATA_PASSWORD: /run/secrets/APP_ROOT_PASSWORD
      APP_HOST_EMAIL: APP_ROOT_EMAIL
      APP_HOST_USERNAME: /run/secrets/APP_ROOT_USERNAME
      APP_HOST_PASSWORD: /run/secrets/APP_ROOT_PASSWORD
      # - APP_DATA_URL=/run/secrets/APP_DATA_URL
    volumes:
      - ${APP_PATH}/website/cert:/app/cert
      - ${APP_PATH}/website/data:/app/data
      - ${APP_PATH}/website/logs:/app/logs
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==${DOCKER_WORKER}
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      resources:
        limits:
          cpus: "2.0"
          memory: "2G"
      labels:
        # Enable Traefik
        - traefik.enable=true
        - traefik.tags=${ENVIRONMENT}
        - traefik.http.services.website.loadbalancer.server.scheme=http
        - traefik.http.serviceswebsite.loadbalancer.server.port=8080
        - traefik.http.routers.website.rule=Host(`${DOMAIN_DEV}`)
        - traefik.http.routers.website.entrypoints=websecure
        - traefik.http.routers.website.tls.certresolver=${TRAEFIK_RESOLVER}
        - traefik.http.routers.website.middlewares=${TRAEFIK_AUTH}
