# version: '3.9'

secrets:
  OAUTH2_TRAEFIK_CLIENT:
    external: true
  OAUTH2_TRAEFIK_COOKIE:
    external: true

# configs:
# volumes:

networks:
  lan-develop:
    external: true
  lan-platform:
    external: true

x-oauth2-base: &oauth2-base
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
  volumes:
    - ${OAUTH2_PATH_CONFIG}/config.cfg:/etc/config.cfg
    - ${OAUTH2_PATH_CONFIG}/libutils.sh:/etc/libutils.sh:ro
    - ${OAUTH2_PATH_CONFIG}/entrypoint.sh:/etc/entrypoint.sh:ro
  networks:
    - lan-${WORKSPACE}
  entrypoint: ["/bin/sh", "/etc/entrypoint.sh"]
  healthcheck:
    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4180/ping"]
    interval: 60s
    timeout: 15s
    retries: 10
    start_period: 120s
  deploy: &oauth2-base-deploy
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - node.role==${DOCKER_WORKER}
        - node.labels.infra==true
    restart_policy:
      condition: on-failure
      delay: 10s
    update_config:
      parallelism: 1
      delay: 15s
      failure_action: rollback
      monitor: 30s
      order: start-first
    rollback_config:
      parallelism: 1
      delay: 10s
      failure_action: continue
      monitor: 30s

services:
  oauth2-traefik:
    <<: *oauth2-base
    secrets:
      - OAUTH2_TRAEFIK_CLIENT
      - OAUTH2_TRAEFIK_COOKIE
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      REALM_ID: ${REALM_ID}
      OAUTH2_TRAEFIK_COOKIE_FILE: /run/secrets/OAUTH2_TRAEFIK_COOKIE
      OAUTH2_PROXY_CLIENT_SECRET_FILE: /run/secrets/OAUTH2_TRAEFIK_CLIENT
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://identity.${DOMAIN_DEV}/realms/${REALM_ID}
      OAUTH2_PROXY_REDIRECT_URL: https://auth.${DOMAIN_DEV}/oauth2/callback
      OAUTH2_PROXY_UPSTREAMS: "https://traefik.${DOMAIN_DEV}"
      OAUTH2_PROXY_CLIENT_ID: "oauth2-traefik"
      OAUTH2_PROXY_COOKIE_NAME: "oauth2-traefik"
      OAUTH2_PROXY_COOKIE_DOMAINS: ".${DOMAIN_DEV}"
      OAUTH2_PROXY_WHITELIST_DOMAINS: ".${DOMAIN_DEV}"
    deploy:
      <<: *oauth2-base-deploy
      labels:
        - traefik.enable=true
        # Security headers middleware
        - traefik.http.middlewares.auth-dev-headers.headers.sslRedirect=true
        - traefik.http.middlewares.auth-dev-headers.headers.stsSeconds=315360000
        - traefik.http.middlewares.auth-dev-headers.headers.browserXssFilter=true
        - traefik.http.middlewares.auth-dev-headers.headers.contentTypeNosniff=true
        - traefik.http.middlewares.auth-dev-headers.headers.forceSTSHeader=true
        - traefik.http.middlewares.auth-dev-headers.headers.sslHost=${DOMAIN_DEV}
        - traefik.http.middlewares.auth-dev-headers.headers.stsIncludeSubdomains=true
        - traefik.http.middlewares.auth-dev-headers.headers.stsPreload=true
        - traefik.http.middlewares.auth-dev-headers.headers.frameDeny=true
        # ForwardAuth middleware
        - traefik.http.middlewares.oauth-traefik-auth.forwardauth.address=https://auth.${DOMAIN_DEV}/oauth2/auth
        - traefik.http.middlewares.oauth-traefik-auth.forwardauth.trustForwardHeader=true
        - traefik.http.middlewares.oauth-traefik-auth.forwardauth.authresponseheaders=X-Auth-Request-User, X-Auth-Request-Email
        # Errors middleware
        - traefik.http.middlewares.oauth-traefik-errors.errors.status=401-403
        - traefik.http.middlewares.oauth-traefik-errors.errors.service=oauth2-traefik-backend
        - traefik.http.middlewares.oauth-traefik-errors.errors.query=/oauth2/sign_in?rd={url}
        # Router to expose /oauth2/* endpoints behind same domain
        - traefik.http.routers.oauth-traefik.rule=Host(`auth.${DOMAIN_DEV}`)
        - traefik.http.routers.oauth-traefik.middlewares=auth-dev-headers
        - traefik.http.routers.oauth-traefik.service=oauth2-traefik-backend
        - traefik.http.routers.oauth-traefik.tls.certresolver=${TRAEFIK_TLS_HTTP}
        - traefik.http.services.oauth2-traefik-backend.loadbalancer.server.port=4180
