# version: '3.9'

#secrets:
# configs:
# volumes:

networks:
  lan-develop:
    external: true
  lan-platform:
    external: true

x-oauth2-base: &oauth2-base
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0-alpine
  volumes:
    - ${OAUTH2_PATH_CONFIG}/config.cfg:/etc/config.cfg
    - ${OAUTH2_PATH_CONFIG}/libutils.sh:/etc/libutils.sh:ro
    - ${OAUTH2_PATH_CONFIG}/entrypoint.sh:/etc/entrypoint.sh:ro
  networks:
    - lan-${WORKSPACE}
    - wan-${WORKSPACE}
  entrypoint: ["/bin/sh", "/etc/entrypoint.sh"]
  healthcheck:
    test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4180/ping"]
    interval: 60s
    timeout: 15s
    retries: 10
    start_period: 120s
  deploy: &oauth2-base-deploy
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - node.role==${DOCKER_WORKER}
        - node.labels.infra==true
    restart_policy:
      condition: on-failure
      delay: 10s
    update_config:
      parallelism: 1
      delay: 15s
      failure_action: rollback
      monitor: 30s
      order: start-first
    rollback_config:
      parallelism: 1
      delay: 10s
      failure_action: continue
      monitor: 30s

services:
  oauth2-traefik:
    <<: *oauth2-base
    secrets:
      - OAUTH2_TRAEFIK_CLIENT
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      REALM_ID: ${REALM_ID}
      OAUTH2_PROXY_CLIENT_SECRET_FILE: /run/secrets/OAUTH2_TRAEFIK_CLIENT
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://identity.${DOMAIN_DEV}/realms/${REALM_ID}
      OAUTH2_PROXY_REDIRECT_URL: traefik.${DOMAIN_DEV}/oauth2/callback
      OAUTH2_PROXY_UPSTREAMS: "https://traefik.${DOMAIN_DEV}"
      OAUTH2_PROXY_CLIENT_ID: "oauth2-traefik"
      OAUTH2_PROXY_COOKIE_NAME: "oauth2-traefik"
      OAUTH2_PROXY_COOKIE_DOMAINS: ".${DOMAIN_DEV}"
      OAUTH2_PROXY_WHITELIST_DOMAINS: ".${DOMAIN_DEV}"
    deploy:
      <<: *oauth2-base-deploy
      labels:
        - traefik.enable=true
        # Router to handle /oauth2/ endpoints
        - traefik.http.routers.oauth.rule=Host(`traefik.${DOMAIN_DEV}`) && PathPrefix(`/oauth2/`)
        - traefik.http.routers.oauth.entrypoints=websecure
        - traefik.http.routers.oauth.tls.certresolver=${TRAEFIK_TLS_HTTP}
        - traefik.http.routers.oauth.tls.domains[0].main=${DOMAIN_DEV}
        - traefik.http.routers.oauth.tls.domains[0].sans=*.${DOMAIN_DEV}
        # Attach security headers middleware
        - traefik.http.routers.oauth.middlewares=auth-headers
        # Service backend
        - traefik.http.services.oauth-backend.loadbalancer.server.port=4180
        # Security headers middleware
        - traefik.http.middlewares.auth-headers.headers.sslRedirect=true
        - traefik.http.middlewares.auth-headers.headers.stsSeconds=315360000
        - traefik.http.middlewares.auth-headers.headers.browserXssFilter=true
        - traefik.http.middlewares.auth-headers.headers.contentTypeNosniff=true
        - traefik.http.middlewares.auth-headers.headers.forceSTSHeader=true
        - traefik.http.middlewares.auth-headers.headers.sslHost=example.com
        - traefik.http.middlewares.auth-headers.headers.stsIncludeSubdomains=true
        - traefik.http.middlewares.auth-headers.headers.stsPreload=true
        - traefik.http.middlewares.auth-headers.headers.frameDeny=true
        # ForwardAuth middleware (checks /oauth2/auth)
        - traefik.http.middlewares.oauth-auth.forwardauth.address=https://auth.${DOMAIN_DEV}/oauth2/auth
        - traefik.http.middlewares.oauth-auth.forwardauth.trustForwardHeader=true
        # Errors middleware (handles 401-403 with redirect to login)
        - traefik.http.middlewares.oauth-errors.errors.status=401-403
        - traefik.http.middlewares.oauth-errors.errors.service=oauth-backend
        - traefik.http.middlewares.oauth-errors.errors.query=/oauth2/sign_in?rd={url}


labels:
  - "traefik.enable=true"

  # Router to expose /oauth2/* endpoints behind same domain
  - "traefik.http.routers.oauth.rule=Host(`a-service.example.com`) && PathPrefix(`/oauth2/`)"
  - "traefik.http.routers.oauth.entrypoints=websecure"
  - "traefik.http.routers.oauth.tls.certresolver=default"
  - "traefik.http.routers.oauth.middlewares=auth-headers"
  - "traefik.http.services.oauth.loadbalancer.server.port=4180"

  # Security headers (optional)
  - "traefik.http.middlewares.auth-headers.headers.sslRedirect=true"
  - "traefik.http.middlewares.auth-headers.headers.stsSeconds=315360000"
  - "traefik.http.middlewares.auth-headers.headers.browserXssFilter=true"
  - "traefik.http.middlewares.auth-headers.headers.contentTypeNosniff=true"
  - "traefik.http.middlewares.auth-headers.headers.forceSTSHeader=true"
  - "traefik.http.middlewares.auth-headers.headers.sslHost=example.com"
  - "traefik.http.middlewares.auth-headers.headers.stsIncludeSubdomains=true"
  - "traefik.http.middlewares.auth-headers.headers.stsPreload=true"
  - "traefik.http.middlewares.auth-headers.headers.frameDeny=true"

  # ForwardAuth middleware
  - "traefik.http.middlewares.oauth-auth.forwardauth.address=https://a-service.example.com/oauth2/auth"
  - "traefik.http.middlewares.oauth-auth.forwardauth.trustForwardHeader=true"

  # Errors middleware
  - "traefik.http.middlewares.oauth-errors.errors.status=401-403"
  - "traefik.http.middlewares.oauth-errors.errors.service=oauth"
  - "traefik.http.middlewares.oauth-errors.errors.query=/oauth2/sign_in?rd={url}"
