server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://telemetry:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          host: swarm-node
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - docker: {}
