target: all,alertmanager,overrides-exporter

server:
  log_level: debug

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      bucket_name: metrics
      insecure: true
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"

blocks_storage:
  storage_prefix: blocks
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: metrics
    insecure: true
  tsdb:
    dir: /data/ingester

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://127.0.0.1:8080/alertmanager
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"
  storage:
    s3:
      endpoint: minio:9000
      bucket_name: mimir-rules
      insecure: true

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/alertmanager-config.yaml
  external_url: http://localhost:9009/alertmanager
  sharding-ring:
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"
  storage:
    s3:
      endpoint: minio:9000
      bucket_name: mimir-alerts
      insecure: true

distributor:
  replication_factor: 2  # Ensure this is set to 2 or higher

ingester:
  replication_factor: 2  # Ensure this is set to 2 or higher
  