# version: '3.9'
# image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
# https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/docker-compose.yaml
secrets:
  PLATFORM_USERNAME:
    external: true
  PLATFORM_PASSWORD:
    external: true

# configs:
# volumes:

networks:
  lan-develop:
    external: true
  lan-platform:
    external: true

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  # expose:
  #   - "9000"
  #   - "9001"
  # environment:
    # MINIO_ROOT_USER: minioadmin
    # MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    hostname: minio1
    volumes:
      - ${APP_PATH}/minio/data11:/data1
      - ${APP_PATH}/minio/data12:/data2

  minio2:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    hostname: minio2
    volumes:
      - ${APP_PATH}/minio/data21:/data1
      - ${APP_PATH}/minio/data22:/data2

  minio3:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    hostname: minio3
    volumes:
      - ${APP_PATH}/minio/data31:/data1
      - ${APP_PATH}/minio/data32:/data2

  minio4:
    image: quay.io/minio/minio:RELEASE.2025-05-24T17-08-30Z
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    hostname: minio4
    volumes:
      - ${APP_PATH}/minio/data41:/data1
      - ${APP_PATH}/minio/data42:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
