# This workflow deploys the development environment

name: Build Website for Development

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/website/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/website/**'

jobs:
  build-website:
    uses: huybrechtsxyz/huybrechtsxyz/build/github/_build-website.yml@main
    with:
      environment: development
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}