# This workflow deploys the development environment

name: Build Website for Staging

on:
  workflow_dispatch:

  release:
    types: [prereleased]

jobs:
  build-website:
    uses: huybrechtsxyz/huybrechtsxyz/build/github/_build-website.yml@main
    with:
      environment: staging
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}