server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000_000
  max_block_duration: 5m

storage:
  trace:
    backend: s3
    s3:
      endpoint: minio:9000
      bucket: otel-tracing
      insecure: true

# metrics_generator:
#   storage:
#     path: "/var/tempo-metrics"
#     disabled: true

compactor:
  ring:
    kvstore:
      store: inmemory
  compaction:
    block_retention: 48h