# Loads secrets from Bitwarden and sets them as GitHub Secrets
name: _BitwardenLoadSecrets

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      BITWARDEN_TOKEN:
        required: true
    outputs:
      kamatera_api_key:
        description: "Kamatera API Key"
        value: ${{ jobs.secrets.outputs.kamatera_api_key }}
      kamatera_api_secret:
        description: "Kamatera API Secret"
        value: ${{ jobs.secrets.outputs.kamatera_api_secret }}
      kamatera_private_key:
        description: "Kamatera SSH Private Key"
        value: ${{ jobs.secrets.outputs.kamatera_private_key }}
      kamatera_public_key:
        description: "Kamatera SSH Public Key"
        value: ${{ jobs.secrets.outputs.kamatera_public_key }}
      terraform_api_token:
        description: "Terraform Cloud Token"
        value: ${{ jobs.secrets.outputs.terraform_api_token }}
      app_root_password:
        description: "App Root Password"
        value: ${{ jobs.secrets.outputs.app_root_password }}

jobs:
  secrets:
    name: Load Secrets From Bitwarden
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      kamatera_api_key: ${{ steps.getall.outputs.KAMATERA_API_KEY }}
      kamatera_api_secret: ${{ steps.getall.outputs.KAMATERA_API_SECRET }}
      kamatera_private_key: ${{ steps.getenv.outputs.KAMATERA_PRIVATE_KEY }}
      kamatera_public_key: ${{ steps.getenv.outputs.KAMATERA_PUBLIC_KEY }}
      terraform_api_token: ${{ steps.getall.outputs.TERRAFORM_API_TOKEN }}
      app_root_password: ${{ steps.getenv.outputs.APP_ROOT_PASSWORD }}
    steps:
      # Set up GitHub Secrets
      - name: Get Environment Secrets
        id: getall
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BITWARDEN_TOKEN }}
          secrets: |
            d47e736b-2db8-47d5-b46b-b2c8016ece73 > TERRAFORM_API_TOKEN
            357068b9-9f5f-4f79-940c-b2c8016cb88f > KAMATERA_API_KEY
            6c9295a8-9fa4-4d38-8929-b2c8016d9b43 > KAMATERA_API_SECRET

      # Set up GitHub Secrets for Test Environment
      - name: Get Test Secrets
        id: test
        if: ${{ inputs.environment == 'test' }}
        uses: bitwarden/sm-action@v2
        with:  
          access_token: ${{ secrets.BITWARDEN_TOKEN }}
          secrets: |
            f16fffe2-77b7-4d20-bf6c-b2c9015c71d3 > KAMATERA_PRIVATE_KEY
            6cc5b975-56a9-4d7a-80c7-b2c90151cce0 > KAMATERA_PUBLIC_KEY
            5083ae32-429d-428b-b7df-b2c901441bbb > APP_ROOT_PASSWORD

      # Set up GitHub Secrets for Staging Environment
      - name: Get Staging Secrets
        id: staging
        if: ${{ inputs.environment == 'staging' }}
        uses: bitwarden/sm-action@v2
        with:  
          access_token: ${{ secrets.BITWARDEN_TOKEN }}
          secrets: |
            0c1f1f1c-456b-47d5-aad4-b2c9015ca6dc > KAMATERA_PRIVATE_KEY
            4dc11520-0305-47fd-bd2a-b2c901526d65 > KAMATERA_PUBLIC_KEY
            924b9526-a6cf-43c1-93a9-b2c9014494ae > APP_ROOT_PASSWORD

      # Set up GitHub Secrets for Production Environment
      - name: Get Production Secrets
        id: prod
        if: ${{ inputs.environment == 'production' }}
        uses: bitwarden/sm-action@v2
        with:  
          access_token: ${{ secrets.BITWARDEN_TOKEN }}
          secrets: |
            02ed2dea7-b72e-401b-ae7e-b2c9015cd76e > KAMATERA_PRIVATE_KEY
            ee623c15-a017-44c5-91e0-b2c9015298a9 > KAMATERA_PUBLIC_KEY
            6db5856c-3f7f-4b62-9846-b2c90144cb0b > APP_ROOT_PASSWORD

      # Set up GitHub Secrets for Environments (trick to set the environment variables)
      # #echo "kamatera_private_key=${{ steps.test.outputs.KAMATERA_PRIVATE_KEY }}" >> "$GITHUB_OUTPUT"
      # #echo "kamatera_private_key=${{ steps.staging.outputs.KAMATERA_PRIVATE_KEY }}" >> "$GITHUB_OUTPUT"
      # #echo "kamatera_private_key=${{ steps.prod.outputs.KAMATERA_PRIVATE_KEY }}" >> "$GITHUB_OUTPUT"
      - name: Set Selected Secrets
        id: getenv
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          if [ "${{ inputs.environment }}" = "test" ]; then
            echo "${{ steps.test.outputs.KAMATERA_PRIVATE_KEY }}" > ~/.ssh/kamatera_key
            chmod 600 ~/.ssh/kamatera_key
            echo "kamatera_public_key=${{ steps.test.outputs.KAMATERA_PUBLIC_KEY }}" >> "$GITHUB_OUTPUT"
            echo "app_root_password=${{ steps.test.outputs.APP_ROOT_PASSWORD }}" >> "$GITHUB_OUTPUT"
          
          elif [ "${{ inputs.environment }}" = "staging" ]; then
            echo "${{ steps.staging.outputs.KAMATERA_PRIVATE_KEY }}" > ~/.ssh/kamatera_key
            chmod 600 ~/.ssh/kamatera_key
            echo "kamatera_public_key=${{ steps.staging.outputs.KAMATERA_PUBLIC_KEY }}" >> "$GITHUB_OUTPUT"
            echo "app_root_password=${{ steps.staging.outputs.APP_ROOT_PASSWORD }}" >> "$GITHUB_OUTPUT"
          
          elif [ "${{ inputs.environment }}" = "production" ]; then
            echo "${{ steps.staging.outputs.KAMATERA_PRIVATE_KEY }}" > ~/.ssh/kamatera_key
            chmod 600 ~/.ssh/kamatera_key
            echo "kamatera_public_key=${{ steps.prod.outputs.KAMATERA_PUBLIC_KEY }}" >> "$GITHUB_OUTPUT"
            echo "app_root_password=${{ steps.prod.outputs.APP_ROOT_PASSWORD }}" >> "$GITHUB_OUTPUT"
          
          else
            echo "Unknown environment: ${{ inputs.environment }}"
            exit 1
          fi
