global:
  scrape_interval: 15s  # How often to scrape the metrics

scrape_configs:
  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8080']  # The Traefik service endpoint to scrape metrics from
