global:
  scrape_interval: 15s  # How often to scrape targets by default.

scrape_configs:
  # Scrape metrics from Traefik
  - job_name: "traefik"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["traefik:8080"]

  # Scrape metrics from Consul
  - job_name: "consul"
    metrics_path: "/v1/agent/metrics"
    static_configs:
      - targets: ["consul:8500"]

  # Scrape metrics from Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
