global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:9100']  # Scrape from Traefik service at port 9100
