//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huybrechts.Web.Pages.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huybrechts.Web.Pages.Account.AccountViewModels", typeof(AccountViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with the Terms and Conditions.
        /// </summary>
        public static string AgreeToTerms {
            get {
                return ResourceManager.GetString("AgreeToTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new password..
        /// </summary>
        public static string ConfirmNewPassword_p {
            get {
                return ResourceManager.GetString("ConfirmNewPassword_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given name.
        /// </summary>
        public static string GivenName {
            get {
                return ResourceManager.GetString("GivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your given name..
        /// </summary>
        public static string GivenName_p {
            get {
                return ResourceManager.GetString("GivenName_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New e-mail.
        /// </summary>
        public static string NewEmail {
            get {
                return ResourceManager.GetString("NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email..
        /// </summary>
        public static string NewEmail_p {
            get {
                return ResourceManager.GetString("NewEmail_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password..
        /// </summary>
        public static string NewPassword_p {
            get {
                return ResourceManager.GetString("NewPassword_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old password..
        /// </summary>
        public static string OldPassword_p {
            get {
                return ResourceManager.GetString("OldPassword_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        public static string Password_p {
            get {
                return ResourceManager.GetString("Password_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number..
        /// </summary>
        public static string PhoneNumber_p {
            get {
                return ResourceManager.GetString("PhoneNumber_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your username..
        /// </summary>
        public static string Please_choose_your_username_ {
            get {
                return ResourceManager.GetString("Please choose your username.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code.
        /// </summary>
        public static string RecoveryCode {
            get {
                return ResourceManager.GetString("RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this machine.
        /// </summary>
        public static string RememberMachine {
            get {
                return ResourceManager.GetString("RememberMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ResetPasswordCode {
            get {
                return ResourceManager.GetString("ResetPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your sur name..
        /// </summary>
        public static string Surname_p {
            get {
                return ResourceManager.GetString("Surname_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator code.
        /// </summary>
        public static string TwoFactorCode {
            get {
                return ResourceManager.GetString("TwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error when trying to set phone number..
        /// </summary>
        public static string Unexpected_error_when_trying_to_set_phone_number_ {
            get {
                return ResourceManager.GetString("Unexpected error when trying to set phone number.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code..
        /// </summary>
        public static string VerificationCode_p {
            get {
                return ResourceManager.GetString("VerificationCode_p", resourceCulture);
            }
        }
    }
}
