version: '3.5'

networks:
    intranet:
        driver: overlay

configs:
    elasticsearch:
        file: .\elasticsearch.yml

services: 
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        user: root
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            discovery.type: single-node
        networks:
            - intranet
        # ports:
        #     - "9200:9200"
        #     - "9300:9300"
        configs:
            - source: elasticsearch
              target: /usr/share/elasticsearch/config/elasticsearch.yml
        volumes:
            - ../../../app/elastic/search:/usr/share/elasticsearch/data