//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huybrechts.Web.Pages.Features.Setup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huybrechts.Web.Pages.Features.Setup.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Defaults.
        /// </summary>
        public static string Add_Defaults {
            get {
                return ResourceManager.GetString("Add Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string Add_New {
            get {
                return ResourceManager.GetString("Add New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string Clear_Filter {
            get {
                return ResourceManager.GetString("Clear Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landen.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new country to the system by specifying its details. This will make the country available for selection across different contexts..
        /// </summary>
        public static string CountryCreateInfo {
            get {
                return ResourceManager.GetString("CountryCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Country.
        /// </summary>
        public static string CountryCreateTitle {
            get {
                return ResourceManager.GetString("CountryCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the deletion of this country. Once deleted, the country will no longer be available for selection in any context..
        /// </summary>
        public static string CountryDeleteInfo {
            get {
                return ResourceManager.GetString("CountryDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Country.
        /// </summary>
        public static string CountryDeleteTitle {
            get {
                return ResourceManager.GetString("CountryDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the details of an existing country to ensure it meets the current needs and preferences of your organization..
        /// </summary>
        public static string CountryEditInfo {
            get {
                return ResourceManager.GetString("CountryEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Country.
        /// </summary>
        public static string CountryEditTitle {
            get {
                return ResourceManager.GetString("CountryEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose countries from a preexisting list based on ISO codes and import them into the system. This ensures the use of standardized country codes for consistency and accuracy..
        /// </summary>
        public static string CountryImportInfo {
            get {
                return ResourceManager.GetString("CountryImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Countries from ISO List.
        /// </summary>
        public static string CountryImportTitle {
            get {
                return ResourceManager.GetString("CountryImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage the list of countries available in the system. You can add, edit, or delete countries to ensure the appropriate options are available for various applications..
        /// </summary>
        public static string CountryIndexInfo {
            get {
                return ResourceManager.GetString("CountryIndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Countries.
        /// </summary>
        public static string CountryIndexTitle {
            get {
                return ResourceManager.GetString("CountryIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to add a new currency to the system. You need to specify the currency&apos;s ISO code, name, symbol, and other relevant details. This information will help in standardizing transactions across different regions and ensuring accurate currency conversions..
        /// </summary>
        public static string CurrencyCreateInfo {
            get {
                return ResourceManager.GetString("CurrencyCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Currency.
        /// </summary>
        public static string CurrencyCreateTitle {
            get {
                return ResourceManager.GetString("CurrencyCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page allows you to delete a currency from the system. Before proceeding, make sure the currency is not currently in use in any active transactions or financial records. Deleting a currency is permanent and cannot be undone..
        /// </summary>
        public static string CurrencyDeleteInfo {
            get {
                return ResourceManager.GetString("CurrencyDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a Currency.
        /// </summary>
        public static string CurrencyDeleteTitle {
            get {
                return ResourceManager.GetString("CurrencyDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page, you can modify the details of an existing currency in the system. Update information such as the currency&apos;s name, ISO code, symbol, or conversion rate. Ensure that all fields are correctly filled to maintain data consistency and accuracy..
        /// </summary>
        public static string CurrencyEditInfo {
            get {
                return ResourceManager.GetString("CurrencyEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Currency Details.
        /// </summary>
        public static string CurrencyEditTitle {
            get {
                return ResourceManager.GetString("CurrencyEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this page to import currencies into the system from a preexisting list based on ISO codes. This functionality is designed to streamline the process of adding standardized currencies, ensuring that all entries conform to international standards. Select the desired currencies from the list to add them to your system efficiently..
        /// </summary>
        public static string CurrencyImportInfo {
            get {
                return ResourceManager.GetString("CurrencyImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Currencies from Predefined ISO List.
        /// </summary>
        public static string CurrencyImportTitle {
            get {
                return ResourceManager.GetString("CurrencyImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page displays a comprehensive list of all currencies currently available in the system. From here, you can view details of each currency, such as their names, ISO codes, and conversion rates. Use the available options to add new currencies, edit existing ones, or delete currencies that are no longer needed..
        /// </summary>
        public static string CurrencyIndexInfo {
            get {
                return ResourceManager.GetString("CurrencyIndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Currencies.
        /// </summary>
        public static string CurrencyIndexTitle {
            get {
                return ResourceManager.GetString("CurrencyIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new language to the system by specifying its code, display name, and any other relevant settings. This allows for customized language options to be available across different contexts like countries and projects..
        /// </summary>
        public static string LanguageCreateInfo {
            get {
                return ResourceManager.GetString("LanguageCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Language.
        /// </summary>
        public static string LanguageCreateTitle {
            get {
                return ResourceManager.GetString("LanguageCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the details of an existing language to ensure it meets the current needs and preferences of your organization..
        /// </summary>
        public static string LanguageDeleteInfo {
            get {
                return ResourceManager.GetString("LanguageDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Language.
        /// </summary>
        public static string LanguageDeleteTitle {
            get {
                return ResourceManager.GetString("LanguageDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the deletion of this language. Once deleted, the language will no longer be available for selection in any context..
        /// </summary>
        public static string LanguageEditInfo {
            get {
                return ResourceManager.GetString("LanguageEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Language.
        /// </summary>
        public static string LanguageEditTitle {
            get {
                return ResourceManager.GetString("LanguageEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select languages from a preexisting list based on ISO codes and import them into the system. This feature allows for easy and standardized language management..
        /// </summary>
        public static string LanguageImpiortInfo {
            get {
                return ResourceManager.GetString("LanguageImpiortInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Languages from ISO List.
        /// </summary>
        public static string LanguageImportTitle {
            get {
                return ResourceManager.GetString("LanguageImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Languages.
        /// </summary>
        public static string LanguageIndexInfo {
            get {
                return ResourceManager.GetString("LanguageIndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage the list of available languages for selection in various contexts such as countries, projects, and other entities. You can add, edit, or remove languages to ensure the system meets your organization&apos;s language needs..
        /// </summary>
        public static string LanguageIndexTitle {
            get {
                return ResourceManager.GetString("LanguageIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one of the options in the menu.
        /// </summary>
        public static string MainInfo {
            get {
                return ResourceManager.GetString("MainInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search___ {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se this form to create a new unit of measurement. Ensure all fields are correctly filled out to define the unit’s attributes, including its type, name, and conversion factor..
        /// </summary>
        public static string UnitCreateInfo {
            get {
                return ResourceManager.GetString("UnitCreateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create system unit.
        /// </summary>
        public static string UnitCreateTitle {
            get {
                return ResourceManager.GetString("UnitCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this unit of measurement? This action cannot be undone. Ensure that this unit is not in use before proceeding..
        /// </summary>
        public static string UnitDeleteInfo {
            get {
                return ResourceManager.GetString("UnitDeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete system unit.
        /// </summary>
        public static string UnitDeleteTitle {
            get {
                return ResourceManager.GetString("UnitDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify the details of this unit of measurement. Ensure the changes accurately reflect the intended attributes of the unit, including its type, name, and conversion factor..
        /// </summary>
        public static string UnitEditInfo {
            get {
                return ResourceManager.GetString("UnitEditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit system unit.
        /// </summary>
        public static string UnitEditTitle {
            get {
                return ResourceManager.GetString("UnitEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select and import units from a preexisting list based on ISO codes. This allows you to quickly and accurately add standardized units to the system..
        /// </summary>
        public static string UnitImportInfo {
            get {
                return ResourceManager.GetString("UnitImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Units from ISO List.
        /// </summary>
        public static string UnitImportTitle {
            get {
                return ResourceManager.GetString("UnitImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page displays all the units of measurement currently available. You can view details, create new units, or edit and delete existing ones..
        /// </summary>
        public static string UnitIndexInfo {
            get {
                return ResourceManager.GetString("UnitIndexInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System units.
        /// </summary>
        public static string UnitIndexTitle {
            get {
                return ResourceManager.GetString("UnitIndexTitle", resourceCulture);
            }
        }
    }
}
