version: '3.9'

services:
  sqlite:
    image: keinos/sqlite3:latest
    command: sqlite3 /data/xyz-application.db
    networks:
      - traefik
    ports:
      - "5432:5432"
    volumes:
      - /app/data:/data
    working_dir: /data
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "sqlite3 /data/application-xyz.db -line '.tables'"]
      interval: 30s
      retries: 3
      timeout: 10s
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.tags=test"
        - "traefik.http.routers.sqlite.rule=Host(`test.huybrechts.xyz`) && PathPrefix(`/sqlite`)"
        - "traefik.http.services.sqlite.loadbalancer.server.port=8080"
        - "traefik.http.routers.sqlite.middlewares=authadmin"
        - "traefik.http.routers.sqlite.entrypoints=websecure"
        - "traefik.http.routers.sqlite.tls=true"
        - "traefik.http.routers.sqlite.tls.certresolver=leresolver"