site:
  title: Huybrechts.xyz

content:
  sources:
  - url: https://github.com/huybrechtsxyz/huybrechtsxyz.git
    branches: HEAD
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true