//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huybrechts.Web.Pages.Account.Tenant {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TenantViewModels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TenantViewModels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huybrechts.Web.Pages.Account.Tenant.TenantViewModels", typeof(TenantViewModels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team description.
        /// </summary>
        public static string Description_d {
            get {
                return ResourceManager.GetString("Description_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter enter the team description..
        /// </summary>
        public static string Description_p {
            get {
                return ResourceManager.GetString("Description_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_s {
            get {
                return ResourceManager.GetString("Description_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team ID.
        /// </summary>
        public static string Id_n {
            get {
                return ResourceManager.GetString("Id_n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your team id..
        /// </summary>
        public static string Id_p {
            get {
                return ResourceManager.GetString("Id_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Id_s {
            get {
                return ResourceManager.GetString("Id_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team name.
        /// </summary>
        public static string Name_d {
            get {
                return ResourceManager.GetString("Name_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the team name..
        /// </summary>
        public static string Name_p {
            get {
                return ResourceManager.GetString("Name_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name_s {
            get {
                return ResourceManager.GetString("Name_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team remarks.
        /// </summary>
        public static string Remark_d {
            get {
                return ResourceManager.GetString("Remark_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks about the team..
        /// </summary>
        public static string Remark_p {
            get {
                return ResourceManager.GetString("Remark_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remark_s {
            get {
                return ResourceManager.GetString("Remark_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team status.
        /// </summary>
        public static string State_d {
            get {
                return ResourceManager.GetString("State_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team status.
        /// </summary>
        public static string State_p {
            get {
                return ResourceManager.GetString("State_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State_s {
            get {
                return ResourceManager.GetString("State_s", resourceCulture);
            }
        }
    }
}
