version: '3.9'

services:
  postgres:
    image: postgres
    secrets:
      - app_dbase_name
      - app_host_username
      - app_host_password
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB_FILE: /run/secrets/app_dbase_name
      POSTGRES_USER_FILE: /run/secrets/app_host_username
      POSTGRES_PASSWORD_FILE: /run/secrets/app_host_password
    networks:
      - traefik
    volumes:
      - /app/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ApplicationDB -U root"]
      interval    : 1s
      timeout: 5s
      retries: 10
      start_period: 5s
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  pgadmin:
    image: dpage/pgadmin4
    secrets:
      - app_host_email
      - app_host_password
    environment:
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_EMAIL: webmaster@huybrechts.xyz
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/app_host_password
      SCRIPT_NAME: /pgadmin
    networks:
      - traefik
    volumes:
      - /app/data/pgadmin:/var/lib/pgadmin
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=production"
        - "traefik.http.routers.pgadmin.rule=Host(`huybrechts.xyz`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.pgadmin.middlewares=authadmin"
        - "traefik.http.routers.pgadmin.entrypoints=websecure"
        - "traefik.http.routers.pgadmin.tls=true"
        - "traefik.http.routers.pgadmin.tls.certresolver=leresolver"