version: '3.9'

services:
  postgres:
    image: postgres:v16.1
    secrets:
      - app_dbase_name
      - app_host_username
      - app_host_password
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=/run/secrets/app_dbase_name
      - POSTGRES_USER=/run/secrets/app_host_username
      - POSTGRES_PASSWORD=/run/secrets/app_host_password
    networks:
      - traefik
    volumes:
      - /app/data/dbase:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval    : 1s
      timeout: 5s
      retries: 10
      start_period: 5s
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

  pgadmin:
    image: dpage/pgadmin4
    secrets:
      - app_host_email
      - app_host_password
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=/run/secrets/app_host_email
      - PGADMIN_DEFAULT_PASSWORD=/run/secrets/app_host_password
    networks:
      - traefik
    volumes:
      - /app/data/pgadmin:/var/lib/pgadmin
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=development"
        - "traefik.http.routers.whoami.rule=Host(`develop.huybrechts.xyz`) && PathPrefix(`/pgadmin`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
        - "traefik.http.routers.whoami.middlewares=authadmin"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=leresolver"