//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huybrechts.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huybrechts.Core.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system administrator role.
        /// </summary>
        internal static string Administrator_d {
            get {
                return ResourceManager.GetString("Administrator_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        internal static string Contributor {
            get {
                return ResourceManager.GetString("Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contributor has read/write access to the data.
        /// </summary>
        internal static string Contributor_d {
            get {
                return ResourceManager.GetString("Contributor_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guest can read the data.
        /// </summary>
        internal static string Guest_d {
            get {
                return ResourceManager.GetString("Guest_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manager has privileged access.
        /// </summary>
        internal static string Manager_d {
            get {
                return ResourceManager.GetString("Manager_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member can read/write some of the data.
        /// </summary>
        internal static string Member_d {
            get {
                return ResourceManager.GetString("Member_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A role that does not provide any access.
        /// </summary>
        internal static string None_d {
            get {
                return ResourceManager.GetString("None_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner has administrator access.
        /// </summary>
        internal static string Owner_d {
            get {
                return ResourceManager.GetString("Owner_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        internal static string PlatformProvider_Azure {
            get {
                return ResourceManager.GetString("PlatformProvider_Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure.
        /// </summary>
        internal static string PlatformProvider_Azure_d {
            get {
                return ResourceManager.GetString("PlatformProvider_Azure_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string PlatformProvider_None {
            get {
                return ResourceManager.GetString("PlatformProvider_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No automation.
        /// </summary>
        internal static string PlatformProvider_None_d {
            get {
                return ResourceManager.GetString("PlatformProvider_None_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string State_Active {
            get {
                return ResourceManager.GetString("State_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string State_Active_d {
            get {
                return ResourceManager.GetString("State_Active_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string State_Disabled {
            get {
                return ResourceManager.GetString("State_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string State_Disabled_d {
            get {
                return ResourceManager.GetString("State_Disabled_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling.
        /// </summary>
        internal static string State_Disabling {
            get {
                return ResourceManager.GetString("State_Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling.
        /// </summary>
        internal static string State_Disabling_d {
            get {
                return ResourceManager.GetString("State_Disabling_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string State_New {
            get {
                return ResourceManager.GetString("State_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string State_New_d {
            get {
                return ResourceManager.GetString("State_New_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string State_Pending {
            get {
                return ResourceManager.GetString("State_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string State_Pending_d {
            get {
                return ResourceManager.GetString("State_Pending_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string State_Removed {
            get {
                return ResourceManager.GetString("State_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        internal static string State_Removed_d {
            get {
                return ResourceManager.GetString("State_Removed_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string State_Removing {
            get {
                return ResourceManager.GetString("State_Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string State_Removing_d {
            get {
                return ResourceManager.GetString("State_Removing_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The standard user role.
        /// </summary>
        internal static string User_d {
            get {
                return ResourceManager.GetString("User_d", resourceCulture);
            }
        }
    }
}
