# This is a complete configuration to deploy Loki backed by a s3-compatible API like MinIO for storage.
# Index files will be written locally at /loki/index and, eventually, will be shipped to the storage via tsdb-shipper.
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /loki

schema_config:
  configs:
  - from: 2024-01-01
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  tsdb_shipper:
   active_index_directory: /loki/index
   cache_location: /loki/index_cache
  aws:
    bucketnames: logging
    endpoint: minio:9000
    region: s3_region
    access_key_id: admin
    secret_access_key: password
    insecure: false
    http_config:
      idle_conn_timeout: 90s
      response_header_timeout: 0s
      insecure_skip_verify: false
    s3forcepathstyle: true
