auth_enabled: false  # Disable authentication for local development

server:
  http_listen_port: 3100  # The port for the Loki HTTP API

ingester:
  chunk_idle_period: 5m
  max_chunk_age: 1h
  max_retention: 30d
  wal:
    enabled: true
    dir: /tmp/wal  # Write Ahead Log storage

storage_config:
  aws:
    s3: s3://loki-bucket/chunks  # MinIO S3-compatible storage path for chunks
    access_key_id: ${MINIO_ROOT_USER}   # MinIO access key
    secret_access_key: ${MINIO_ROOT_PASSWORD}  # MinIO secret key
    bucketnames: loki-chunks   # Bucket name for chunks
    endpoint: minio:9000  # MinIO endpoint (docker-compose uses the service name `minio`)
    insecure: true  # Disable SSL for local MinIO

    # Index storage (can also be configured similarly to chunks)
    index:
      s3: s3://loki-bucket/index
      bucketnames: loki-index  # Bucket name for index
      endpoint: minio:9000  # MinIO endpoint
      insecure: true  # Disable SSL for local MinIO

table_manager:
  retention_deletes_enabled: true
  retention_period: 30d  # Retain logs for 30 days
