server:
  http_listen_port: 9009
  http_listen_address: 0.0.0.0:9009
  log_level: debug

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      insecure: true
      #access_key_id: admin
      #secret_access_key: password

blocks_storage:
  backend: s3
  s3:
    bucket_name: metrics

alertmanager_storage:
  s3:
    bucket_name: mimir-alerts

ruler_storage:
  s3:
    bucket_name: mimir-rules
