server:
  http_listen_port: 9000
  grpc_listen_port: 9095
  log_level: debug

limits_config:
  max_chunks_per_query: 5000
  max_query_length: 60
  max_returned_streams: 100

cortex:
  frontend:
    frontend_url: "http://localhost:9000"
  alertmanager:
    alertmanager_url: "http://alertmanager:9093"

common:
  storage:
    backend: s3
    s3:
      endpoint: minio:9000
      insecure: true

distributor:
  ring:
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"

ingester:
  chunk_idle_period: 5m
  max_chunk_age: 1h
  max_chunks_per_query: 5000
  num_parallel_queries: 1
  ring:
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"

query_frontend:
  max_concurrent: 1000

querier:
  query_ingesters_within: 12h

store-gateway:
  sharding-ring:
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"

blocks_storage:
  backend: s3
  s3:
    bucket_name: metrics

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention:
    daily: 30d
    weekly: 30d
  ring:
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://127.0.0.1:8080/alertmanager
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"

ruler_storage:
  s3:
    bucket_name: mimir-rules

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/mimir/alertmanager-config.yml
  external_url: http://localhost:9009/alertmanager
  sharding-ring:
    kvstore:
      store: consul
      consul:
        http_addr: "http://consul:8500"
        consistency: "strong"
        prefix: "mimir/ring"

alertmanager_storage:
  s3:
    bucket_name: mimir-alerts
