server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

storage:
  trace:
    backend: s3
    s3:
      endpoint: minio:9000
      bucket: tracing
      access_key: ${MINIO_ROOT_USER}
      secret_key: ${MINIO_ROOT_PASSWORD}
      insecure: true

compactor:
  compaction:
    block_retention: 24h
