version: '3.9'

services:
  # https://github.com/Tecnativa/docker-socket-proxy
  # Security-enhanced proxy for the Docker Socket
  # Giving access to your Docker socket could mean giving root access to your host, or even to your whole swarm, 
  # but some services require hooking into that socket to react to events, etc. 
  # Using this proxy lets you block anything you consider those services should not do.
  socketproxy:
    image: tecnativa/docker-socket-proxy:latest
    restart: unless-stopped
    environment:
      NETWORKS: 1
      SERVICES: 1
      CONTAINERS: 1
      TASKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket_proxy