# version: '3.9'

secrets:
  PLATFORM_USERNAME:
    external: true
  PLATFORM_PASSWORD:
    external: true

# configs:
# volumes:

networks:
  lan-develop:
    external: true
  lan-platform:
    external: true

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    volumes:
      - ${APP_PATH_CONF}/keycloak/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ${APP_PATH_CONF}/keycloak/real.${WORKSPACE}.json:/tmp/realm.template.json
    networks:
      - lan-${WORKSPACE}
    secrets:
      - PLATFORM_USERNAME
      - PLATFORM_PASSWORD
      - TRAEFIK_CLIENTID
      - TRAEFIK_SECRET
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      ENVIRONMENT: ${ENVIRONMENT}
      REALM_ID: ${REALM_ID}
      REALM_NAME: ${REALM_NAME}
      KC_LOG: console #,file
      KC_LOG_LEVEL: INFO
      #KC_LOG_FILE: /home/keycloak.log
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HOSTNAME: https://auth.${DOMAIN_DEV}
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_METRICS_HISTOGRAMS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_TRACING_ENABLED: "true"
      KC_TRACING_PROPAGATORS: tracecontext,baggage
      KC_TRACING_SAMPLER: always_on
      KC_TRACING_ENDPOINT: http://telemetry:4317
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${PLATFORM_SQL_NAME}
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME_FILE: /run/secrets/PLATFORM_USERNAME
      KC_DB_PASSWORD_FILE: /run/secrets/PLATFORM_PASSWORD
      KC_BOOTSTRAP_ADMIN_USERNAME_FILE: /run/secrets/PLATFORM_USERNAME
      KC_BOOTSTRAP_ADMIN_PASSWORD_FILE: /run/secrets/PLATFORM_PASSWORD
      TRAEFIK_CLIENTID_FILE: /run/secrets/TRAEFIK_CLIENTID
      TRAEFIK_SECRET: /run/secrets/TRAEFIK_SECRET
    entrypoint: /usr/local/bin/entrypoint.sh --proxy-headers forwarded --hostname-debug=true --features=opentelemetry
    healthcheck:
      test: ["CMD", "bash", "-c", "[ $$(/opt/keycloak/bin/kcadm.sh get serverinfo --realm Keycloak --fields '*' --server http://localhost:8080/admin/serverinfo 2>&1 | grep Unauthorized | wc -l ) -eq 1 ]"]
      interval: 60s
      timeout: 15s
      retries: 10
      start_period: 120s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==${DOCKER_WORKER}
          - node.labels.infra==true
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 10s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      labels:
        - traefik.enable=true
        - traefik.http.services.keycloak.loadbalancer.server.scheme=http
        - traefik.http.services.keycloak.loadbalancer.server.port=8080
        - traefik.http.routers.keycloak.rule=Host(`auth.${DOMAIN_DEV}`)
        - traefik.http.routers.keycloak.entrypoints=websecure
        - traefik.http.routers.keycloak.tls.certresolver=${TRAEFIK_TLS_DNS}
