// <auto-generated />
using System;
using Huybrechts.App.Features.Setup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Huybrechts.Infra.Npgsql.Migrations.Setup
{
    [DbContext(typeof(SetupContext))]
    [Migration("20240826073230_CreateSetupUnit")]
    partial class CreateSetupUnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Huybrechts.Core.Setup.SetupUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasComment("Primary Key");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("A unique code representing the unit, standard across all instances.");

                    b.Property<DateTime>("CreatedDT")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date time created");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("A detailed description of the unit.");

                    b.Property<decimal>("Factor")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)")
                        .HasComment("A multiplication factor used to convert this unit to the base unit.");

                    b.Property<bool>("IsBase")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether this unit is the base unit for its type.");

                    b.Property<DateTime?>("ModifiedDT")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Modified time created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("The unique name of the unit within its type.");

                    b.Property<int>("Precision")
                        .HasColumnType("integer")
                        .HasComment("Number of decimal places for the unit.");

                    b.Property<int>("PrecisionType")
                        .HasColumnType("integer")
                        .HasComment("Determines how values are rounded according to the System.Decimal Rounding enum.");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasComment("Additional remarks or comments about the unit.");

                    b.Property<string>("SearchIndex")
                        .HasColumnType("text")
                        .HasComment("This field will store the normalized, concatenated values for searching");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<int>("UnitType")
                        .HasMaxLength(32)
                        .HasColumnType("integer")
                        .HasComment("Gets or sets the type of the unit (e.g., Height, Weight, Volume, System, etc.).");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SearchIndex");

                    b.ToTable("SetupUnit", t =>
                        {
                            t.HasComment("Represents a measurement unit used for different types such as height, weight, volume, etc.");
                        });

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });
#pragma warning restore 612, 618
        }
    }
}
