# Docker Compose for the staging environment
version: '3.9'

networks:
  internet:
  localnet:

services:
  website:
    image: "huybrechts/website:latest"
    environment:
      - "ASPNETCORE_ENVIRONMENT=${APP_ENVIRONMENT}"
      - "DOTNET_RUNNING_IN_CONTAINER=true"
    networks:
      - "internet"
    ports:
      - 5080:5080
      - 5433:5433
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`${APP_BASEURL}`)"
      - "traefik.http.routers.portal.service=website"
      - "traefik.http.routers.portal.entrypoints=websecure"
      - "traefik.http.routers.portal.tls.certresolver=letsencrypt"
      - "traefik.http.routers.portal.tls.domains[0].main=${APP_BASEURL}"
      - "traefik.http.routers.portal.middlewares=sslheader"