# Docker Compose for the staging environment
version: '3.9'

services:
  website:
    image: huybrechts/website:${APP_ENVIRONMENT}
    environment:
      - ASPNETCORE_ENVIRONMENT=${WEB_ENVIRONMENT}
      - DOTNET_RUNNING_IN_CONTAINER=1
    networks:
      - traefik
    volumes:
      - "/app/data:/app/data"
      - "/app/logs:/app/logs"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=${APP_ENVIRONMENT}"
        - "traefik.http.routers.website.rule=Host(`${APP_HOST_URL}`)"
        - "traefik.http.services.website.loadbalancer.server.port=8080"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.routers.website.tls.certresolver=leresolver"