# Docker Compose for the staging environment
version: '3.9'

services:
  website:
    image: huybrechts/website:production
    secrets:
      - app_host_username
      - app_host_password
      - app_data_provider
      - app_data_url
      - app_data_name
      - app_data_username
      - app_data_password
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=1
      - APP_HOST_USERNAME_FILE=/run/secrets/app_host_username
      - APP_HOST_PASSWORD_FILE=/run/secrets/app_host_password
      - APP_DATA_PROVIDER=/run/secrets/app_data_provider
      - APP_DATA_URL=/run/secrets/app_data_url
      - APP_DATA_NAME=/run/secrets/app_data_name
      - APP_DATA_USERNAME=/run/secrets/app_data_username
      - APP_DATA_PASSWORD=/run/secrets/app_data_password
    networks:
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=production"
        - "traefik.http.routers.website.rule=Host(`huybrechts.xyz`)"
        - "traefik.http.services.website.loadbalancer.server.port=8080"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.tls=true"
        - "traefik.http.routers.website.tls.certresolver=leresolver"