//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huybrechts.App.Features.Wiki {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Huybrechts.App.Features.Wiki.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki with namespace and path already exists.
        /// </summary>
        public static string DUPLICATE_WIKI_PATH {
            get {
                return ResourceManager.GetString("DUPLICATE_WIKI_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find wiki with ID {0}.
        /// </summary>
        public static string INVALID_WIKI_ID {
            get {
                return ResourceManager.GetString("INVALID_WIKI_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # New Wiki Page
        ///
        ///Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        ///
        ///## Key Points
        ///
        ///- Sed do eiusmod tempor
        ///- Ut enim ad minim veniam
        ///- Duis aute irure dolor
        ///
        ///Or create a link to a wiki [[{namespace}:{page}|{linktext}]].
        ///
        ///## More Information
        ///
        ///For more details, visit [Wikipedia](https://www.wikipedia.org)..
        /// </summary>
        public static string NEW_WIKI_CONTENT {
            get {
                return ResourceManager.GetString("NEW_WIKI_CONTENT", resourceCulture);
            }
        }
    }
}
