entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: "public"
  swarm:
    constraints: "Label(`traefik.tags`, `test`)"

api:
  dashboard: true

certificatesResolvers:
  leresolver:
    acme:
      email: "webmaster@huybrechts.xyz"
      storage: "/app/cert/acme.json"
      dnsChallenge:
        provider: "versio"
        delayBeforeCheck: 0
        usernameFile: "/run/secrets/VERSIO_USERNAME"
        passwordFile: "/run/secrets/VERSIO_PASSWORD"
        endpointFile: "/run/secrets/VERSIO_ENDPOINT"

log:
  level: "INFO"
  format: "json"
  filePath: "/app/logs/traefik.log"
  maxSize: 5
  maxAge: 5

accessLog:
  format: "json"
  filePath: "/app/logs/traefik-access.log"

ping: {}

# Secrets and environment variables need to be managed externally,
# such as in a Docker secret file or environment configuration.

