entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: "public"
  swarm:
    constraints: "Label(`traefik.tags`, `develop`)"

api:
  insecure: true
  dashboard: true

ping: true

certificatesResolvers:
  tmpresolver:
    acme:
      email: "webmaster@huybrechts.xyz"
      storage: "/app/data/acme.json"
      tlschallenge:

log:
  level: "DEBUG"
  format: "json"
  filePath: "/app/logs/traefik.log"
  maxSize: 5
  maxAge: 5

accessLog:
  format: "json"
  filePath: "/app/logs/traefik-access.log"
