version: '3.5'

networks:
    intranet:
        driver: overlay

configs:
    kibanaconfig:
        file: .\kibana.yml

services: 
    kibana:
        image: docker.elastic.co/kibana/kibana:7.7.0
        networks:
            - intranet
        # ports:
        #     - "5601:5601"
        configs:
            - source: kibanaconfig
              target: /usr/share/kibana/config/kibana.yml