@startuml

!define ENTITY(name) class name << (E,#FFAAAA) >>
!define MULTITENANT(name) class name << (M,#FFFFAA) >>

ENTITY(Entity) {
    +Id: int
    +TenantId: int
}

MULTITENANT(WikiPage) {
    +Namespace: string
    +Page: string
    +Title: string
    +Tags: string?
    +SearchIndex: string?
    +Content: string
}

WikiPage -|> Entity

note right of WikiPage::Namespace
    Represents the category or group the page is part of,
    such as 'UserGuide', 'Admin', etc.
end note

note right of WikiPage::Page
    The path defines how the page can be accessed through
    the web, for example, 'how/to/catch/path'.
end note

note right of WikiPage::Title
    The title is a short, descriptive name for the 
    content of the page.
end note

note right of WikiPage::Tags
    Keywords or categories for the project.
end note

note right of WikiPage::SearchIndex
    This field will store the normalized, 
    concatenated values for searching.
end note

note right of WikiPage::Content
    The content is stored in markdown format, 
    allowing for rich text editing and display.
end note

@enduml
