secrets:
  APP_ROOT_PASSWORD:
    external: true
  TRAEFIK_CLIENTID:
    external: true
  TRAEFIK_SECRET:
    external: true
  VERSIO_USERNAME:
    external: true
  VERSIO_PASSWORD:
    external: true

services:

  traefik:
    image: "traefik:v3.3.6"
    command: traefik --configFile=/etc/traefik/traefik-config.yml
    secrets:
      - VERSIO_USERNAME
      - VERSIO_PASSWORD
      - TRAEFIK_CLIENTID
      - TRAEFIK_SECRET
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      ENVIRONMENT: ${ENVIRONMENT}
      VERSIO_ENDPOINT: ${VERSIO_ENDPOINT}
      VERSIO_USERNAME_FILE: /run/secrets/VERSIO_USERNAME
      VERSIO_PASSWORD_FILE: /run/secrets/VERSIO_PASSWORD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_PATH}/traefik/conf/traefik-config.yml:/etc/traefik/traefik-config.yml
      - ${APP_PATH}/traefik/data:/app/data
      - ${APP_PATH}/traefik/logs:/app/logs
    ports:
      - 80:80
      - 443:443
    networks:
      - wan
      - lan
    # healthcheck:
    #   test: ["CMD", "traefik", "healthcheck", "--ping"]
    #   interval: 15s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 30s
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      # resources:
      #   limits:
      #     cpus: "1.0"
      #     memory: "512M"
      labels:
        # Enable Traefik
        - traefik.enable=true
        - traefik.tags=${ENVIRONMENT}
        # Redirection Middleware
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        # Basic Auth Middleware
        - traefik.http.middlewares.basic-auth.basicauth.users=root:$$apr1$$QWdnNA46$$ERyQkE85h.jRxDlkEFTcU.
        # Keycloak OpenId Plugin Middleware
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.KeycloakURL=http://iam.${DOMAIN_DEV}:8080/
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.ClientIDFile=/run/secrets/TRAEFIK_CLIENTID
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.ClientSecretFile=/run/secrets/TRAEFIK_SECRET
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.KeycloakRealm=huybrechts
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.Scope=openid profile email
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.TokenCookieName=AUTH_TOKEN
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.UseAuthHeader=false
        - traefik.http.middlewares.openid-auth.plugin.keycloakopenid.IgnorePathPrefixes=/favicon.ico
        # Traefik dashboard
        - traefik.http.services.traefik.loadbalancer.server.scheme=http
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.traefik.rule=Host(`proxy.${DOMAIN_DEV}`)
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.tls.certresolver=${TRAEFIK_RESOLVER}
        - traefik.http.routers.traefik.middlewares=${TRAEFIK_MIDDLEWARES}

  consul:
    image: hashicorp/consul:1.20
    environment:
      DATACENTER: ${DATACENTER}
      DOMAIN_DEV: ${DOMAIN_DEV}
      ENVIRONMENT: ${ENVIRONMENT}
      HOSTNAMEID: ${HOSTNAMEID}
      CONSUL_BIND_INTERFACE: eth0
    command:
      - consul
      - agent
      - -config-dir=/consul/config
      - -data-dir=/consul/data
      - -bootstrap-expect=${DOCKER_MANAGERS}
      - -datacenter=${DATACENTER}
      - -node=${HOSTNAMEID}
      - -advertise={{ GetPrivateIP }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_PATH}/consul/conf:/consul/config
      - ${APP_PATH}/consul/data:/consul/data
    networks:
      - lan
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      # resources:
      #   limits:
      #     cpus: "1.0"
      #     memory: "1G"
      labels:
        - traefik.enable=true
        - traefik.tags=${ENVIRONMENT}
        - traefik.http.services.consul.loadbalancer.server.scheme=http
        - traefik.http.services.consul.loadbalancer.server.port=8500
        - traefik.http.routers.consul.rule=Host(`config.${DOMAIN_DEV}`)
        - traefik.http.routers.consul.entrypoints=websecure
        - traefik.http.routers.consul.tls.certresolver=${TRAEFIK_RESOLVER}
        - traefik.http.routers.consul.middlewares=${TRAEFIK_MIDDLEWARES}

  postgres:
    image: postgres
    secrets:
      - APP_ROOT_PASSWORD
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: xyzdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD_FILE: /run/secrets/APP_ROOT_PASSWORD
    volumes:
      - ${APP_PATH}/postgres/data:/var/lib/postgresql/data/pgdata
    networks:
      - lan
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -d xyzdb -U root"]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 10
    #   start_period: 5s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==${DOCKER_WORKER}
          - node.labels.postgres==true
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      # resources:
      #   limits:
      #     cpus: "2.0"
      #     memory: "2G"
      labels:
        - traefik.enable=false

  postgres-init:
    image: postgres
    secrets:
      - APP_ROOT_PASSWORD
    environment:
      POSTGRES_DB: xyzdb
      POSTGRES_URL: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD_FILE: /run/secrets/APP_ROOT_PASSWORD
    entrypoint: usr/local/bin/entrypoint.sh
    volumes:
      - ${APP_PATH}/postgres/conf/postgres-entry.sh:/usr/local/bin/entrypoint.sh:ro
      - ${APP_PATH}/postgres/conf/postgres-init.sql:/usr/local/bin/postgres-init.sql:ro
    networks:
      - lan
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==${DOCKER_WORKER}
          - node.labels.postgres==true
      restart_policy:
        condition: none # Ensure this runs only once
      labels:
        - traefik.enable=false

  pgadmin:
    image: dpage/pgadmin4
    secrets:
      - APP_ROOT_PASSWORD
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      ENVIRONMENT: ${ENVIRONMENT}
      PGADMIN_LISTEN_PORT: 9080
      PGADMIN_DEFAULT_EMAIL: ${APP_ROOT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/APP_ROOT_PASSWORD
      SCRIPT_NAME: /pgadmin
    volumes:
      - ${APP_PATH}/postgres/admin:/var/lib/pgadmin
    networks:
      - lan
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "http://localhost:9080/pgadmin"]
    #   interval: 15s
    #   retries: 3
    #   timeout: 5s
    #   start_period: 10s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==${DOCKER_WORKER}
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      # resources:
      #   limits:
      #     cpus: "2.0"
      #     memory: "2G"
      labels:
        # Enable Traefik
        - traefik.enable=true
        - traefik.tags=${ENVIRONMENT}
        - traefik.http.services.pgadmin.loadbalancer.server.scheme=http
        - traefik.http.services.pgadmin.loadbalancer.server.port=9080
        - traefik.http.routers.pgadmin.rule=Host(`db.${DOMAIN_DEV}`) && PathPrefix(`/pgadmin`)
        - traefik.http.routers.pgadmin.entrypoints=websecure
        - traefik.http.routers.pgadmin.tls.certresolver=${TRAEFIK_RESOLVER}
        - traefik.http.routers.pgadmin.middlewares=${TRAEFIK_MIDDLEWARES}

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    secrets:
      - APP_ROOT_PASSWORD
    environment:
      DOMAIN_DEV: ${DOMAIN_DEV}
      ENVIRONMENT: ${ENVIRONMENT}
      KC_LOG: console #,file
      KC_LOG_LEVEL: INFO
      #KC_LOG_FILE: /home/keycloak.log
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HOSTNAME: https://iam.${DOMAIN_DEV}
      KC_HOSTNAME_STRICT: "false"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_METRICS_HISTOGRAMS_ENABLED: "true"
      KC_EVENT_METRICS_USER_ENABLED: "true"
      KC_TRACING_ENABLED: "true"
      KC_TRACING_PROPAGATORS: tracecontext,baggage
      KC_TRACING_SAMPLER: always_on
      KC_TRACING_ENDPOINT: http://telemetry:4317
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: xyzdb
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD_FILE: /run/secrets/APP_ROOT_PASSWORD
      KC_BOOTSTRAP_ADMIN_USERNAME: root
      KC_BOOTSTRAP_ADMIN_PASSWORD_FILE: /run/secrets/APP_ROOT_PASSWORD
    entrypoint: usr/local/bin/entrypoint.sh --proxy-headers forwarded --hostname-debug=true --features=opentelemetry --import-realm
    volumes:
      - ${APP_PATH}/keycloak/conf/keycloak-entry.sh:/usr/local/bin/entrypoint.sh
      #- ${APP_PATH}/keycloak/conf/keycloak-realm.json:/opt/keycloak/data/import/keycloak-realm.json
    networks:
      - lan
    # healthcheck:
    #   test: ["CMD", "bash", "-c", "[ $$(/opt/keycloak/bin/kcadm.sh get serverinfo --realm Keycloak --fields '*' --server http://localhost:8080/admin/serverinfo 2>&1 | grep Unauthorized | wc -l ) -eq 1 ]"]
    #   interval: 15s
    #   retries: 3
    #   timeout: 5s
    #   start_period: 30s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==${DOCKER_WORKER}
        preferences:
          - spread: node.id
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 60s
      update_config:
        parallelism: 1
        delay: 15s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 30s
      # resources:
      #   limits:
      #     cpus: "2.0"
      #     memory: "2G"
      labels:
        # Enable Traefik
        - traefik.enable=true
        - traefik.tags=${ENVIRONMENT}
        - traefik.http.services.keycloak.loadbalancer.server.scheme=http
        - traefik.http.services.keycloak.loadbalancer.server.port=8080
        - traefik.http.routers.keycloak.rule=Host(`iam.${DOMAIN_DEV}`)
        - traefik.http.routers.keycloak.entrypoints=websecure
        - traefik.http.routers.keycloak.tls.certresolver=${TRAEFIK_RESOLVER}
        - traefik.http.routers.keycloak.middlewares=${TRAEFIK_MIDDLEWARES}

networks:
  wan:
    external: true
  lan:
    external: true