# https://docs.docker.com/compose/multiple-compose-files/extends/
# Docker Compose for the staging environment
version: '3.9'

services:
  traefik:
    extends:
      file: traefik.yml
      service: traefik
  website:
    extends:
      file: website.yml
      service: website
  whoami:
    extends:
      file: whoami.yml
      service: whoami

networks:
  traefik:
    external: true