# Docker Compose for the test environment
#
# Environment Variables
# =======================================
# =======================================
#
version: '3.9'

services:

  consul:
    image: consul:1.15.4
    container_name: consul
    command:
      - consul
      - agent
      - -dev
      - -data-dir=/consul/data
      - -config-dir=/consul/config
      - -config-file=/consul/config/config-consul.develop.json
    networks:
      - public
    volumes:
      - consul-conf:/consul/config
      - consul-data:/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:

  consul-conf:
    driver: local
    driver_opts:
      type: none
      device: ../.app/consul/conf
      o: bind
  consul-data:
    driver: local
    driver_opts:
      type: none
      device: ../.app/consul/data
      o: bind

networks:
  public:
    driver: bridge
  private:
    driver: bridge

#secrets:

#configs:
