# https://docs.docker.com/compose/multiple-compose-files/extends/
# Docker Compose for the staging environment
version: '3.9'

services:
  traefik:
    extends:
      file: traefik.development.yml
      service: traefik
  whoami:
    extends:
      file: whoami.development.yml
      service: whoami
  website:
    extends:
      file: website.development.yml
      service: website
  postgres:
    extends:
      file: postgres.development.yml
      service: postgres
  pgadmin:
    extends:
      file: postgres.development.yml
      service: pgadmin

networks:
  traefik:
    external: true

secrets:
  app_dbase_name:
    file: app_dbase_name
  app_host_username:
    file: app_host_username
  app_host_email:
    file: app_host_email
  app_host_password:
    file: app_host_password