# https://docs.docker.com/compose/multiple-compose-files/extends/
# Docker Compose for the staging environment
version: '3.9'

services:
  traefik:
    extends:
      file: traefik-compose.yml
      service: traefik
  website:
    extends:
      file: website-compose.yml
      service: website
  whoami:
    extends:
      file: whoami-compose.yml
      service: whoami

networks:
  traefik:
    external: true