# https://docs.docker.com/compose/multiple-compose-files/extends/
# Docker Compose for the staging environment
version: '3.9'

services:
  traefik:
    extends:
      file: traefik.development.yml
      service: traefik
  website:
    extends:
      file: website.development.yml
      service: website
  whoami:
    extends:
      file: whoami.development.yml
      service: whoami

networks:
  traefik-dev:
    external: true