# Docker Compose for the development environment
version: '3.9'

networks:

  public:
    driver: bridge
  private:
    driver: bridge

services:

  traefik:
    image: "traefik:v3.1.6"
    container_name: traefik
    command:
      # Logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      # Enable the Traefik log, for configurations and errors
      - --log=true
      - --log.level=DEBUG
      - --log.format=json
      - --log.maxsize=5
      - --log.maxage=5
      - --log.filePath=/app/logs/traefik.log
      # Checking the Health of Your Traefik Instances
      - --ping=true
      # Enable the access log, with HTTP requests
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.filepath=/app/logs/traefik-access.log
      # Prometheus metrics
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addRoutersLabels=true
      - --metrics.prometheus.addServicesLabels=true
      - --metrics.prometheus.buckets=0.1,0.3,1.2,5.0
      # Consul configuration
      - --providers.consulCatalog=true
      - --providers.consulCatalog.cache=true
      - --providers.consulCatalog.refreshInterval=30s
      - --providers.consulCatalog.endpoint.address=http://consul:8500
      - --providers.consulCatalog.endpoint.scheme=http
      - --providers.consulCatalog.exposedByDefault=false
      - --providers.consulCatalog.defaultRule=Host(`localhost`)
      # Entry points
      - --entrypoints.web.address=:80
      # Specifies the number of concurrent streams per connection that each client is allowed to initiate for http/2
      # Docker configuration
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=public
      # Dashboard. Optional. Default: true. 
      - --api
      - --api.dashboard=true
    ports:
      - "80:80"
      - "433:433"
    networks:
      - public
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../.app/traefik/cert:/app/cert"
      - "../.app/traefik/logs:/app/logs"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
    labels:
      # Enable for test
      - "traefik.enable=true"
      - "traefik.tags=develop"
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`proxy.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"

  # https://developer.hashicorp.com/consul/docs/agent#running-an-agent
  consul:
    image: consul:1.15.4
    container_name: consul
    environment:
      CONSUL_LOCAL_CONFIG: '{ "datacenter": "develop", "log_level": "DEBUG", "bind_addr": "0.0.0.0",  "client_addr": "0.0.0.0"}'
    command: 
      - "consul"
      - "agent"
      - "-server"
      - "-ui"
      - "-data-dir=/consul/data"
      - "-config-dir=/consul/config"
    ports:
      - "8500:8500" # Web UI and API
      - "8600:8600/udp"
    networks:
      - public
    volumes:
      - ../.app/consul/conf:/consul/config
      - ../.app/consul/data:/consul/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
    labels:
      - "traefik.enable=true"
      - "traefik.tags=develop"
      - "traefik.http.routers.consul.rule=Host(`localhost`)"
      - "traefik.http.routers.consul.entrypoints=web"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    depends_on:
      - minio
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.external-url=http://localhost:9090
    ports:
      - "9090:9090"  # Prometheus web UI
    networks:
      - public
    volumes:
      - "../.app/prometheus/conf:/etc/prometheus"
      - "../.app/prometheus/data:/prometheus"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/-/healthy"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - "traefik.enable=false" # grafana is used as UI

  minio:
    image: "minio/minio:latest"
    container_name: minio
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "password"
      MINIO_REGION: "eu-frankfurt-test"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # MinIO Dataservice
      - "9001:9001"  # MinIO Console (optional)
    networks:
      - public
    volumes:
      - "../.app/minio/data:/data"
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`localhost`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.entrypoints=web"

  thanos-sidecar:
    image: "quay.io/thanos/thanos:v0.37.0"
    container_name: thanos-sidecar
    depends_on:
      prometheus:
        condition: service_healthy
      minio:
        condition: service_healthy
    command:
      - sidecar
      - "--tsdb.path=/prometheus"
      - "--objstore.config-file=/etc/thanos/thanos-bucket.yml"
      - "--prometheus.url=http://prometheus:9090"
    networks:
      - public
    volumes:
      - ../.app/prometheus/data:/prometheus
      - ../.app/prometheus/conf:/etc/thanos
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:10902/-/healthy"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=false"

  thanos-query:
    image: "quay.io/thanos/thanos:v0.37.0"
    container_name: thanos-query
    depends_on:
      prometheus:
        condition: service_healthy
      minio:
        condition: service_healthy
      thanos-sidecar:
        condition: service_healthy
    command:
      - query
      - "--http-address=0.0.0.0:9091"
      - "--store=thanos-sidecar:10901"
      - "--store=minio:9000"
    ports:
      - "9091:9091"
    networks:
      - public
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9091/-/healthy"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=false"
