# https://docs.docker.com/compose/multiple-compose-files/extends/
# Docker Compose for the staging environment
version: '3.9'

networks:
  internet:
    external: true
  localnet:

services:
  traefik:
    extends:
      file: traefik/docker-compose.yml
      service: traefik
  
  portainer-agent:
    extends:
      file: portainer/docker-compose.yml
      service: portainer-agent

  portainer-server:
    extends:
      file: portainer/docker-compose.yml
      service: portainer-server
      
  website:
    extends:
      file: website/docker-compose.yml
      service: website      
