# https://docs.docker.com/compose/multiple-compose-files/extends/
# Docker Compose for the staging environment
version: '3.9'

services:
  traefik:
    extends:
      file: traefik.staging.yml
      service: traefik
  whoami:
    extends:
      file: whoami.staging.yml
      service: whoami
  sqlite:
    extends:
      file: sqlite.staging.yml
      service: sqlite

networks:
  traefik:
    external: true

secrets:
  APP_AUTH_GOOGLE:
    external: true
  APP_DATA_NAME:
    external: true
  APP_DATA_PASSWORD:
    external: true
  APP_DATA_URL:
    external: true
  APP_DATA_USERNAME:
    external: true
  APP_HOST_EMAIL:
    external: true
  APP_HOST_PASSWORD:
    external: true
  APP_HOST_SERVER:
    external: true
  APP_HOST_USERNAME:
    external: true
  APP_HOST_PORT:
    external: true
  APP_SMTP_OPTIONS:
    external: true
  REGISTRY_USERNAME:
    external: true
  REGISTRY_PASSWORD:
    external: true