# Docker Compose for the development environment
version: '3.9'

networks:

  traefik:
    external: true
  intranet:
    driver: bridge

services:

  traefik:
    image: "traefik:v3.1.6"
    container_name: traefik
    depends_on:
      - consul
    command:
      # Logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      # Enable the Traefik log, for configurations and errors
      - --log=true
      - --log.level=DEBUG
      - --log.format=json
      - --log.maxsize=5
      - --log.maxage=5
      - --log.filePath=/app/logs/traefik.log
      # Checking the Health of Your Traefik Instances
      - --ping=true
      # Enable the access log, with HTTP requests
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.filepath=/app/logs/traefik-access.log
      # Prometheus metrics
      - --metrics.prometheus=true
      - --metrics.prometheus.addEntryPointsLabels=true
      - --metrics.prometheus.addRoutersLabels=true
      - --metrics.prometheus.addServicesLabels=true
      # Consul configuration
      - --providers.consulCatalog=true
      - --providers.consulCatalog.cache=true
      - --providers.consulCatalog.refreshInterval=30s
      - --providers.consulCatalog.endpoint.address=http://consul:8500
      - --providers.consulCatalog.endpoint.scheme=http
      - --providers.consulCatalog.exposedByDefault=false
      - --providers.consulCatalog.defaultRule=Host(`localhost`)
      # Entry points
      - --entrypoints.web.address=:80
      # Specifies the number of concurrent streams per connection that each client is allowed to initiate for http/2
      # Docker configuration
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik
      # Dashboard. Optional. Default: true. 
      - --api
      - --api.dashboard=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../.app/traefik/cert:/app/cert"
      - "../.app/traefik/logs:/app/logs"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.tags=develop"
      - "traefik.http.routers.traefik.rule=Host(`proxy.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  consul:
    image: consul:1.15.4
    container_name: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: agent -server -bootstrap -ui -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - traefik
    volumes:
      - ../.app/consul/data:/consul/data
      - ../.app/consul/conf/minio.json:/consul/config/minio.json
      - ../.app/consul/conf/pgadmin.json:/consul/config/pgadmin.json
      - ../.app/consul/conf/postgres.json:/consul/config/postgres.json
      - ../.app/consul/conf/prometheus.json:/consul/config/prometheus.json
      - ../.app/consul/conf/traefik.json:/consul/config/traefik.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://consul.localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.tags=develop"
      - "traefik.http.routers.consul.rule=Host(`consul.localhost`)"
      - "traefik.http.routers.consul.entrypoints=web"
      - "traefik.http.services.consul.loadbalancer.server.port=8500"

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - "9090:9090"  # Prometheus web interface
    volumes:
      - ../.app/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus configuration
      - ../.app/prometheus/data:/prometheus
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tags=develop"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.entrypoints=web"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  postgres:
    image: postgres
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - intranet
    volumes:
      - ../.app/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U ${POSTGRES_USER}"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s

  postgres_prometheus:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres_prometheus
    command:
      - "--config.file=/config/postgres_exporter.yml"
    environment:
      DATA_SOURCE_USER: admin
      DATA_SOURCE_PASS: password
      DATA_SOURCE_NAME: "postgresql://postgres:5432/mydb?sslmode=disable"
    ports:
      - "9187:9187"
    volumes:
      - ../.app/prometheus/conf/postgres_exporter.yml:/config/postgres_exporter.yml:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_LISTEN_PORT: 8800
      PGADMIN_DEFAULT_EMAIL: webmaster@huybrechts.xyz
      PGADMIN_DEFAULT_PASSWORD: password
      SCRIPT_NAME: /pgadmin
    ports:
      - "8800:8800"
    networks:
      - traefik
      - intranet
    volumes:
      - ../.app/pgadmin/data:/var/lib/pgadmin
    labels:
      - "traefik.enable=true"
      - "traefik.tags=test"
      - "traefik.http.routers.pgadmin.rule=Host(`admin.localhost`) && PathPrefix(`/pgadmin`)"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=8800"
      - "traefik.http.routers.pgadmin.entrypoints=web"

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
    volumes:
      - ../.app/minio/data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.tags=develop"
      - "traefik.http.routers.minio.rule=Host(`minio.localhost`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio.entrypoints=web"
