# https://docs.docker.com/compose/multiple-compose-files/extends/

# url.com:8080/dashboard       -> Traefik dashboard
# url.com:8080/api             -> Traefik api

# Docker Compose for the staging environment
version: '3.9'

networks:
  internet:
    external: true
  agentnet:
    external: true
  localnet:
    external: false

services:
  traefik:
    extends:
      file: traefik/docker-compose.yml
      service: traefik
  
  agent:
    extends:
      file: portainer/docker-compose.yml
      service: agent

  portainer:
    extends:
      file: portainer/docker-compose.yml
      service: portainer
      
  website:
    extends:
      file: website/docker-compose.yml
      service: website      
