version: '3.9'

networks:
  internet:
  localnet:

services:
  image: portainer/portainer-ce:latest
  command: -H unix:///var/run/docker.sock
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    # Frontend
    - "traefik.enable=true"
    - "traefik.http.routers.frontend.rule=Host(`${APP_BASEURL}\portainer`)"
    - "traefik.http.routers.frontend.entrypoints=websecure"
    - "traefik.http.services.frontend.loadbalancer.server.port=9000"
    - "traefik.http.routers.frontend.service=frontend"
    - "traefik.http.routers.frontend.tls.certresolver=leresolver"
    # Edge
    - "traefik.http.routers.edge.rule=Host(`${APP_BASEURL}\edge`)"
    - "traefik.http.routers.edge.entrypoints=websecure"
    - "traefik.http.services.edge.loadbalancer.server.port=8000"
    - "traefik.http.routers.edge.service=edge"
    - "traefik.http.routers.edge.tls.certresolver=leresolver"