version: '3.9'

services:
  whoami:
    image: traefik/whoami:v1.10
    command:
      - --port=8080
    networks:
      - traefik-stg
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.tags=staging"
        - "traefik.http.routers.whoami.rule=Host(`staging.huybrechts.xyz`) && PathPrefix(`/whoami`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=8080"
        - "traefik.http.routers.whoami.middlewares=authadmin"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=leresolver"