version: '3.9'

services:
  whoami:
    image: traefik/whoami:v1.10
    command:
      - --port=8080
    networks:
      - traefik
    deploy:
      labels:
        # Explicitly instruct Traefik to expose this service
        - "traefik.enable=true"
        # Change the host url here
        - "traefik.http.routers.whoami.rule=Host(`whoami.example.com`)"
        - "traefik.http.services.whoami.loadbalancer.server.port=8082"
        - "traefik.http.routers.whoami.middlewares=basicauth"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls=true"
        - "traefik.http.routers.whoami.tls.certresolver=leresolver"