@startuml Platform CD

class Platform {
}

class Region {
}

Platform "1" -- "0..*" Region

class Service {
}

Platform "1" -- "0..*" Service

class Product {
}

Platform "1" -- "0..*" Product

class Rate {
}

Product "1" -- "0..*" Rate
Region "1" -- "0..*" Rate
Service "1" -- "0..*" Rate

@enduml