@startuml Platform CD

class Platform {
}

class Region {
}

Platform "1" -- "0..*" Region






class Location {
}


class Service {
}



class SearchRate {
}

class Product {
}

class Rate {
}

class RateUnit {
}

Platform "1" -- "0..*" SearchRate

Platform "1" -- "0..*" Service


Location "1" -- "0..*"Region

Platform "1" -- "0..*" Product
Product "1" -- "0..1" Service
Product "1" -- "0..1" Region
Product "1" -- "0..*" Rate
Rate "1" -- "0..*" RateUnit 

@enduml