# This workflow will build the documentation folder, create and publish the container to the registry

name: Reusable - Build Documentation

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Convert AsciiDocs to HTML
        run: |
          docker run -v  ${{ github.workspace }}/docs:/documents/ asciidoctor/docker-asciidoctor asciidoctor *.adoc

      - name: Build Docker image
        run: |
          echo "FROM nginx" > Dockerfile
          echo "COPY . /usr/share/nginx/html" >> Dockerfile
          docker build -t asciidocs:${{ inputs.environment }} .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/asciidocs:${{ inputs.environment }}
      