# This reusable workflow will pull the container from the registry

name: Reusable - Deploy Container Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      component:
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      APP_HOST_SERVER:
        required: true
      APP_HOST_USERNAME:
        required: true
      APP_HOST_PASSWORD:
        required: true
      APP_HOST_PORT:
        required: true
         
jobs:
  deploy-image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Pull docker container
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APP_HOST_PORT }}
          script: |
            cd /;
            cd /app/${{ inputs.environment }};
            echo '${{ secrets.REGISTRY_PASSWORD }}' | docker login --username '${{ secrets.REGISTRY_USERNAME }}' --password-stdin &> /dev/null;
            docker-compose -f ${{ inputs.component }}-compose.yml pull &> /app/${{ inputs.environment }}/logs/compose.log;