# This reusable workflow will deploy a container image to an environment

name: Reusable - Deploy Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      component:
        required: true
        type: string
    secrets:
      HOST_SERVER:
        required: true
      HOST_USERNAME:
        required: true
      HOST_PASSWORD:
        required: true
      HOST_PORT:
        required: true

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: List files for component
        run: |
          ls ${{ github.workspace }}/src/${{ inputs.component }}
      - name: SSH Deploy Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          source: "src/${{ inputs.component }}/**"
          strip_components: 2
          overwrite: true
          target: "/app/${{ inputs.environment }}"
      - name: SSH Deploy Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          source: "src/${{ inputs.environment }}.env,src/compose.yml"
          strip_components: 1
          overwrite: true
          target: "/app/${{ inputs.environment }}"
