# This reusable workflow will initialize the server it runs on

name: Reusable - Initialize Server

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      HOST_SERVER:
        required: true
      HOST_USERNAME:
        required: true
      HOST_PASSWORD:
        required: true
      HOST_PORT:
        required: true

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: SSH Remote Command
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            docker network create --driver=overlay internet