# Build and Deploy Jobs
name: Build and Deploy Jobs

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      initialize:
        required: true
        type: string
      rebuild:
        required: true
        type: string
    secrets:
      APP_DATA_USERNAME: 
        required: true
      APP_DATA_PASSWORD:
        required: true
      APP_HOST_SERVER:
        required: true
      APP_HOST_PORT:
        required: true
      APP_HOST_USERNAME:
        required: true
      APP_HOST_PASSWORD:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      APP_AUTH_GOOGLE:
        required: true
      APP_DATA_NAME:
        required: true
      APP_DATA_URL:
        required: true
      APP_HOST_EMAIL:
        required: true
      APP_SMTP_OPTIONS:
        required: true

jobs:
  initialize-server:
    name: Initialize Server Job
    if: inputs.initialize == 'true'
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_task_initialize.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}

  update-server:
    name: Update Server Job
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_task_update.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      APP_DATA_USERNAME: ${{ secrets.APP_DATA_USERNAME }}
      APP_DATA_PASSWORD: ${{ secrets.APP_DATA_PASSWORD }}
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_AUTH_GOOGLE: ${{ secrets.APP_AUTH_GOOGLE }}
      APP_DATA_NAME: ${{ secrets.APP_DATA_NAME }}
      APP_DATA_URL: ${{ secrets.APP_DATA_URL }}
      APP_HOST_EMAIL: ${{ secrets.APP_HOST_EMAIL }}
      APP_SMTP_OPTIONS: ${{ secrets.APP_SMTP_OPTIONS }}

  build-website:
    name: Build Website Job
    if: inputs.rebuild == 'true'
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_task_docker.yml@main
    with:
      environment: ${{ inputs.environment }}
      imagename: 'huybrechts/website'
      sourcepath: 'website'
      projectname: 'Huybrechts.Web'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-config:
    name: Deploy Configuration Job
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_task_configuration.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}

  deploy-stack-rebuild:
    name: Deploy Docker Swarm Stack (Rebuild)
    if: inputs.rebuild == 'true'
    needs: [deploy-config, build-website]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_task_deploy.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      APP_DATA_USERNAME: ${{ secrets.APP_DATA_USERNAME }}
      APP_DATA_PASSWORD: ${{ secrets.APP_DATA_PASSWORD }}
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}

  deploy-stack-nobuild:
    name: Deploy Docker Swarm Stack (Build)
    if: inputs.rebuild != 'true'
    needs: [deploy-config]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_task_deploy.yml@main
    with:
      environment: ${{ inputs.environment }}
    secrets:
      APP_DATA_USERNAME: ${{ secrets.APP_DATA_USERNAME }}
      APP_DATA_PASSWORD: ${{ secrets.APP_DATA_PASSWORD }}
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
