# Build and Deploy Jobs
name: _BuildAndDeploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      initialize:
        required: true
        type: string
      rebuild:
        required: true
        type: string
    secrets:
      BITWARDEN_TOKEN:
        required: true

jobs:
  terraform:
    name: Terraform Swarm Cluster
    if: inputs.initialize == 'true'
    uses: ./.github/workflows/_task-terraform.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  
  initialize:
    name: Initialize Swarm Cluster
    needs: [terraform]
    if: inputs.initialize == 'true'
    uses: ./.github/workflows/_task-initialize.yml
    with:
      environment: ${{ inputs.environment }}
      tf_output: ${{ needs.terraform.outputs.tf_output }}
    secrets: inherit

  configure:
    name: Configure Swarm Cluster
    needs: [initialize]
    if: ${{ inputs.initialize != 'true' || needs.initialize.result == 'success' }}
    uses: ./.github/workflows/_task-configure.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
