# Build and Deploy Jobs
name: _BuildAndDeploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      initialize:
        required: true
        type: string
      rebuild:
        required: true
        type: string
    secrets:
      BITWARDEN_TOKEN:
        required: true

jobs:
  terraform:
    name: Terraform Swarm Cluster
    if: inputs.initialize == 'true'
    uses: ./.github/workflows/_task-terraform.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
  
  initialization:
    name: Initialize Swarm Cluster
    needs: [terraform]
    uses: ./.github/workflows/_task-initialize.yml
    with:
      environment: ${{ inputs.environment }}
      tf_output: ${{ needs.terraform.outputs.tf_output }}
    secrets: inherit

  initskip:
    name: Skip Initialization
    if: inputs.initialize == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip Initialization
        run: echo "Skipping initialization as per input."

  configuration:
    name: Configure Swarm Cluster
    needs: [initialization, initskip]
    uses: ./.github/workflows/_task-configure.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
