# This reusable workflow
name: Reusable Build and Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      initialize:
        required: true
        type: string
    secrets:
      APP_HOST_SERVER:
        required: true
      APP_HOST_USERNAME:
        required: true
      APP_HOST_PASSWORD:
        required: true
      APP_HOST_PORT:
        required: true
      APP_HOST_EMAIL:
        required: true
      APP_DATA_URL:
        required: true
      APP_DATA_NAME:
        required: true
      APP_DATA_USERNAME:
        required: true
      APP_DATA_PASSWORD:
        required: true
      APP_AUTH_GOOGLE:
        required: true
      APP_SMTP_OPTIONS:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  init-server:
    name: Initialize Server Job
    if: inputs.initialize == 'true'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Initialize server script
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APPHOST_PORT }}
          script: |
            cd /;
            echo "Initializing server";

  update-server:
    name: Update Server Job
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Update server script
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APPHOST_PORT }}
          script: |
            cd /
            # Function to create a path if it does not already exist
            function createpath() {
              local newpath="$1"
              if [ ! -d "$newpath" ]; then
                mkdir -p "$newpath"
                if [ $? -ne 0 ]; then
                  echo "Error: Failed to create directory '$newpath'"
                  return 1  # Return non-zero status to indicate failure
                fi
                chmod 777 "$newpath"
              fi
              return 0  # Return zero status to indicate success
            }
            # Function to check if a Docker secret is in use
            function issecretinuse() {
              local secret_name="$1"
              # Check if any services are using the secret
              if docker service ls --format '{{.Name}}' | xargs -I {} docker service inspect {} --format '{{range .Spec.TaskTemplate.ContainerSpec.Secrets}}{{if eq .SecretName "'"$secret_name"'"}}{{.SecretName}}{{end}}{{end}}' | grep -q "$secret_name"; then
                return 0
              fi
              # Check if any containers are using the secret
              if docker ps --format '{{.Names}}' | xargs -I {} docker inspect {} --format '{{range .Mounts}}{{if eq .Type "secret"}}{{.Name}}{{end}}{{end}}' | grep -q "$secret_name"; then
                return 0
              fi
              return 1
            }
            # Function to create or update a Docker secret
            function createsecret() {
              local secret_label="$1"
              local secret_name="$2"
              local secret_value="$3"
              echo "Inspecting $secret_label"
              # Check if the secret already exists
              if docker secret inspect "$secret_name" &> /dev/null; then
                echo "$secret_label - Secret already exists"
                # Check if the secret is in use
                echo "Checking if $secret_label is in use"
                if issecretinuse "$secret_name"; then
                  echo "$secret_label is in use by services or containers. Skipping deletion."
                  return 0
                fi
                # Remove the old secret
                echo "Removing old $secret_label"
                docker secret rm "$secret_name"
              fi
              # Check if secret_name is not empty and create a new secret
              if [ -n "$secret_name" ]; then
                echo "Creating new $secret_label"
                echo "$secret_value" | docker secret create "$secret_name" -
              else
                echo "$secret_label - Not defined"
              fi
            }
            echo Updating server
            echo Creating application directories
            cd /
            createpath "/app"
            createpath "/app/cert"
            createpath "/app/conf"
            createpath "/app/data"
            createpath "/app/data/pgdata"
            createpath "/app/data/pgadmin"
            sudo chown -R 5050:5050 /app/data/pgadmin
            createpath "/app/docs"
            createpath "/app/logs"
            #Create the traefik network on docker
            echo Traefik Network
            docker network inspect traefik --format {{.Id}} 2>/dev/null \
              || docker network create --driver overlay traefik
            #Create the docker secrets
            createsecret "Google Login" "APP_AUTH_GOOGLE" '${{ secrets.APP_AUTH_GOOGLE }}'
            createsecret "Database Name" "APP_DATA_NAME" '${{ secrets.APP_DATA_NAME }}'
            createsecret "Database Username" "APP_DATA_USERNAME" '${{ secrets.APP_DATA_USERNAME }}'
            createsecret "Database Password" "APP_DATA_PASSWORD" '${{ secrets.APP_DATA_PASSWORD }}'
            createsecret "Database Connection" "APP_DATA_URL" '${{ secrets.APP_DATA_URL }}'
            createsecret "Server Email" "APP_HOST_EMAIL" '${{ secrets.APP_HOST_EMAIL }}'
            createsecret "Server Password" "APP_HOST_PASSWORD" '${{ secrets.APP_HOST_PASSWORD }}'
            createsecret "Server Port" "APP_HOST_PORT" '${{ secrets.APP_HOST_PORT }}'
            createsecret "Server Uri" "APP_HOST_SERVER" '${{ secrets.APP_HOST_SERVER }}'
            createsecret "Server Username" "APP_HOST_USERNAME" '${{ secrets.APP_HOST_USERNAME }}'
            createsecret "SMTP Server Options" "APP_SMTP_OPTIONS" '${{ secrets.APP_SMTP_OPTIONS }}'
  build-website:
    name: Build Website Image
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build website
        run: dotnet build --no-restore
      - name: Test website
        run: dotnet test --no-build --verbosity normal
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: huybrechts/website
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}
            type=sha
            type=raw,value=${{ inputs.environment }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./src/website/Huybrechts.Web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-component:
    name: Deploy Component Configuration
    needs: [update-server]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        component: [traefik, whoami, sqlite, website]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Deploy configuration files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APP_HOST_PORT }}
          source: "src/${{ matrix.component }}/*${{ inputs.environment }}*"
          strip_components: 2
          overwrite: true
          target: "/app"
  
  deploy-generic:
    name: Deploy Generic Configuration
    needs: [update-server]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Deploy generic files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APP_HOST_PORT }}
          source: "src/compose.${{ inputs.environment }}.yml"
          strip_components: 1
          overwrite: true
          target: "/app"

  deploy-stack:
    name: Deploy Docker Swarm Stack
    needs: [build-website, deploy-component, deploy-generic]
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Update docker stack
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APP_HOST_PORT }}
          script_stop: true
          script: |
            cd /
            cd /app
            if [ -f compose.${{ inputs.environment }}.yml ]; then
              mv compose.${{ inputs.environment }}.yml compose.yml
            fi
            echo DOCKER DEPLOY
            docker stack deploy -c <(docker-compose -f compose.yml config) app &> /dev/null