# Update Server Task
name: Update Server Task

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      APP_DATA_USERNAME: 
        required: true
      APP_DATA_PASSWORD:
        required: true
      APP_HOST_SERVER:
        required: true
      APP_HOST_PORT:
        required: true
      APP_HOST_USERNAME:
        required: true
      APP_HOST_PASSWORD:
        required: true
      APP_AUTH_GOOGLE:
        required: true
      APP_DATA_NAME:
        required: true
      APP_DATA_URL:
        required: true
      APP_HOST_EMAIL:
        required: true
      APP_SMTP_OPTIONS:
        required: true

jobs:
  update-server:
    name: Update Server Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Update server script
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.APP_HOST_SERVER }}
        username: ${{ secrets.APP_HOST_USERNAME }}
        password: ${{ secrets.APP_HOST_PASSWORD }}
        port: ${{ secrets.APP_HOST_PORT }}
        script: |
          cd /
          # Function to create a path if it does not already exist
          function createpath() {
          local newpath="$1"
          if [ ! -d "$newpath" ]; then
              mkdir -p "$newpath"
              if [ $? -ne 0 ]; then
              echo "Error: Failed to create directory '$newpath'"
              return 1  # Return non-zero status to indicate failure
              fi
              #chmod 777 "$newpath"
              sudo chmod -R 777 "$newpath"
          fi
          return 0  # Return zero status to indicate success
          }
          # Function to check if a Docker secret is in use
          function issecretinuse() {
          local secret_name="$1"
          # Check if any services are using the secret
          if docker service ls --format '{{.Name}}' | xargs -I {} docker service inspect {} --format '{{range .Spec.TaskTemplate.ContainerSpec.Secrets}}{{if eq .SecretName "'"$secret_name"'"}}{{.SecretName}}{{end}}{{end}}' | grep -q "$secret_name"; then
              return 0
          fi
          # Check if any containers are using the secret
          if docker ps --format '{{.Names}}' | xargs -I {} docker inspect {} --format '{{range .Mounts}}{{if eq .Type "secret"}}{{.Name}}{{end}}{{end}}' | grep -q "$secret_name"; then
              return 0
          fi
          return 1
          }
          # Function to create or update a Docker secret
          function createsecret() {
          local secret_label="$1"
          local secret_name="$2"
          local secret_value="$3"
          echo "Inspecting $secret_label"
          # Check if the secret already exists
          if docker secret inspect "$secret_name" &> /dev/null; then
              echo "$secret_label - Secret already exists"
              # Check if the secret is in use
              echo "Checking if $secret_label is in use"
              if issecretinuse "$secret_name"; then
              echo "$secret_label is in use by services or containers. Skipping deletion."
              return 0
              fi
              # Remove the old secret
              echo "Removing old $secret_label"
              docker secret rm "$secret_name"
          fi
          # Check if secret_name is not empty and create a new secret
          if [ -n "$secret_name" ]; then
              echo "Creating new $secret_label"
              echo "$secret_value" | docker secret create "$secret_name" -
          else
              echo "$secret_label - Not defined"
          fi
          }
          # Start of scripts
          # sudo chown -R 5050:5050 /app/data/pgadmin
          echo Updating server
          echo Creating application directories
          cd /
          createpath "/app"
          createpath "/app/cert"
          createpath "/app/data/consul"
          createpath "/app/data/pgdata"
          createpath "/app/data/pgadmin"
          createpath "/app/docs"
          createpath "/app/logs"
          sudo chown -R 5050:5050 /app/data/*
          #Create the traefik network on docker
          echo Traefik Network
          docker network inspect traefik --format {{.Id}} 2>/dev/null \
          || docker network create --driver overlay traefik
          #Create the docker secrets
          createsecret "Google Mail" "APP_AUTH_GOOGLE" '${{ secrets.APP_AUTH_GOOGLE }}'
          createsecret "Database Name" "APP_DATA_NAME" '${{ secrets.APP_DATA_NAME }}'
          createsecret "Database URL" "APP_DATA_URL" '${{ secrets.APP_DATA_URL }}'
          createsecret "Server Email" "APP_HOST_EMAIL" '${{ secrets.APP_HOST_EMAIL }}'
          createsecret "SMTP Options" "APP_SMTP_OPTIONS" '${{ secrets.APP_SMTP_OPTIONS }}'
          #Create the docker secrets
          createsecret "Database Username" "APP_DATA_USERNAME" '${{ secrets.APP_DATA_USERNAME }}'
          createsecret "Database Password" "APP_DATA_PASSWORD" '${{ secrets.APP_DATA_PASSWORD }}'
          createsecret "Server Server" "APP_HOST_SERVER" '${{ secrets.APP_HOST_SERVER }}'
          createsecret "Server Port" "APP_HOST_PORT" '${{ secrets.APP_HOST_PORT }}'
          createsecret "Server Username" "APP_HOST_USERNAME" '${{ secrets.APP_HOST_USERNAME }}'
          createsecret "Server Password" "APP_HOST_PASSWORD" '${{ secrets.APP_HOST_PASSWORD }}'
