# Deploy Docker Swarm Stack Task
name: Deploy Swarm Stack Task

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      APP_HOST_SERVER:
        required: true
      APP_HOST_PORT:
        required: true
      APP_HOST_USERNAME:
        required: true
      APP_HOST_PASSWORD:
        required: true

jobs:
  deploy-stack:
    name: Deploy Swarm Stack Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Update docker stack
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APP_HOST_PORT }}
          script_stop: true
          script: |
            set -e
            cd /
            cd /app
            # Fetch the Swarm manager IPs
            DOCKER_SWARM_IPS=$(docker node ls --filter "role=manager" --format "{{.ID}}" | while read id; do
              docker node inspect $id --format '{{ .Status.Addr }}'
            done)
            # Create a retry-join string
            RETRY_JOIN=""
            for ip in $MANAGER_IPS; do
              RETRY_JOIN="$RETRY_JOIN,http://$ip:8500"
            done
            # Remove the leading comma
            DOCKER_SWARM_IPS=${RETRY_JOIN:1}
            export DOCKER_SWARM_IPS
            # Set the appropriate security on the application subdirectories
            echo APPY SECURITY
            sudo chmod -R 600 /app/traefik/data
            sudo chmod -R 777 /app/traefik/logs
            # Redeploy the new docker compose
            echo DOCKER DEPLOY
            docker stack deploy -c compose.${{ inputs.environment }}.yml app &> /app/logs/deploy-stack.log
