# Update Server Task
# 
#   app
#   ├── consul +                 # Consul
#   │ ├── conf +                 #   Consul conf
#   │ ├── data +                 #   Consul data
#   ├── postgres +               # Postgres and PGAdmin
#   │ ├── admin +                #   PGAdmin data
#   │ ├── data +                 #   Postgres databases
#   ├── traefik +                # Traefik
#   │ ├── data +                 #   Traefik data
#   │ ├── logs +                 #   Traefik data
#
name: Update Server Task

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      KEYCLOAK_USER:
        required: true
      KEYCLOAK_PASSWORD:
        required: true
      MINIO_ROOT_USER: 
        required: true
      MINIO_ROOT_PASSWORD:
        required: true
      POSTGRES_USER:
        required: true
      POSTGRES_PASSWORD:
        required: true
      PGADMIN_USER:
        required: true
      PGADMIN_PASSWORD:
        required: true
      SERVER_ENDPOINT:
        required: true
      SERVER_PORT:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true
      VERSIO_USERNAME:
        required: true
      VERSIO_PASSWORD:
        required: true
      VERSIO_ENDPOINT:
        required: true

jobs:
  update-server:
    name: Update Server Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Update server script
      uses: appleboy/ssh-action@v1.0.2
      with:
        host: ${{ secrets.SERVER_ENDPOINT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /
          # Function to create a path if it does not already exist
          function createpath() {
          local newpath="$1"
          if [ ! -d "$newpath" ]; then
              mkdir -p "$newpath"
              if [ $? -ne 0 ]; then
              echo "Error: Failed to create directory '$newpath'"
              return 1  # Return non-zero status to indicate failure
              fi
              #chmod 777 "$newpath"
              sudo chmod -R 777 "$newpath"
          fi
          return 0  # Return zero status to indicate success
          }
          # Function to check if a Docker secret is in use
          function issecretinuse() {
          local secret_name="$1"
          # Check if any services are using the secret
          if docker service ls --format '{{.Name}}' | xargs -I {} docker service inspect {} --format '{{range .Spec.TaskTemplate.ContainerSpec.Secrets}}{{if eq .SecretName "'"$secret_name"'"}}{{.SecretName}}{{end}}{{end}}' | grep -q "$secret_name"; then
              return 0
          fi
          # Check if any containers are using the secret
          if docker ps --format '{{.Names}}' | xargs -I {} docker inspect {} --format '{{range .Mounts}}{{if eq .Type "secret"}}{{.Name}}{{end}}{{end}}' | grep -q "$secret_name"; then
              return 0
          fi
          return 1
          }
          # Function to create or update a Docker secret
          function createsecret() {
          local secret_label="$1"
          local secret_name="$2"
          local secret_value="$3"
          echo "Inspecting $secret_label"
          # Check if the secret already exists
          if docker secret inspect "$secret_name" &> /dev/null; then
              echo "$secret_label - Secret already exists"
              # Check if the secret is in use
              echo "Checking if $secret_label is in use"
              if issecretinuse "$secret_name"; then
              echo "$secret_label is in use by services or containers. Skipping deletion."
              return 0
              fi
              # Remove the old secret
              echo "Removing old $secret_label"
              docker secret rm "$secret_name"
          fi
          # Check if secret_name is not empty and create a new secret
          if [ -n "$secret_name" ]; then
              echo "Creating new $secret_label"
              echo "$secret_value" | docker secret create "$secret_name" -
          else
              echo "$secret_label - Not defined"
          fi
          }
          # Start of scripts
          echo Updating server
          echo Creating application directories
          cd /
          createpath "/app"
          createpath "/app/scripts"
          createpath "/app/consul"
          createpath "/app/consul/conf"
          createpath "/app/consul/data"
          createpath "/app/postgres"
          createpath "/app/postgres/admin"
          createpath "/app/postgres/data"
          createpath "/app/postgres/backups"
          createpath "/app/traefik"
          createpath "/app/traefik/data"
          createpath "/app/traefik/logs"
          # createpath "/app/prometheus"
          # createpath "/app/prometheus/conf"
          # createpath "/app/prometheus/data"
          #Create the PUBLIC network on docker
          echo Public Network
          docker network inspect public --format {{.Id}} 2>/dev/null \
          || docker network create --driver overlay public
          #Create the PRIVATE network on docker
          echo Private Network
          docker network inspect private --format {{.Id}} 2>/dev/null \
          || docker network create --driver overlay private
          #Create the docker secrets
          createsecret "Keycloak Username" "KEYCLOAK_USER" '${{ secrets.KEYCLOAK_USER }}'
          createsecret "Keycloak Password" "KEYCLOAK_PASSWORD" '${{ secrets.KEYCLOAK_PASSWORD }}'
          createsecret "Minio Username" "MINIO_ROOT_USER" '${{ secrets.MINIO_ROOT_USER }}'
          createsecret "Minio Password" "MINIO_ROOT_PASSWORD" '${{ secrets.MINIO_ROOT_PASSWORD }}'
          createsecret "Postgres User" "POSTGRES_USER" '${{ secrets.POSTGRES_USER }}'
          createsecret "Postgres Password" "POSTGRES_PASSWORD" '${{ secrets.POSTGRES_PASSWORD }}'
          createsecret "PG Admin User" "PGADMIN_USER" '${{ secrets.PGADMIN_USER }}'
          createsecret "PG Admin Password" "PGADMIN_PASSWORD" '${{ secrets.PGADMIN_PASSWORD }}'
          createsecret "Server Endpoint" "SERVER_ENDPOINT" '${{ secrets.SERVER_ENDPOINT }}'
          createsecret "Server Port" "SERVER_PORT" '${{ secrets.SERVER_PORT }}'
          createsecret "Server Username" "SERVER_USERNAME" '${{ secrets.SERVER_USERNAME }}'
          createsecret "Server Password" "SERVER_PASSWORD" '${{ secrets.SERVER_PASSWORD }}'
          createsecret "Versio Username" "VERSIO_USERNAME" '${{ secrets.VERSIO_USERNAME }}'
          createsecret "Versio Password" "VERSIO_PASSWORD" '${{ secrets.VERSIO_PASSWORD }}'
          createsecret "Versio Endpoint" "VERSIO_ENDPOINT" '${{ secrets.VERSIO_ENDPOINT }}'
