# Deploy Configuration Task
name: Deploy Configuration Task

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      APP_HOST_SERVER:
        required: true
      APP_HOST_PORT:
        required: true
      APP_HOST_USERNAME:
        required: true
      APP_HOST_PASSWORD:
        required: true

jobs:
  deploy-configuration:
    name: Deploy Configuration Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Deploy generic files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.APP_HOST_SERVER }}
        username: ${{ secrets.APP_HOST_USERNAME }}
        password: ${{ secrets.APP_HOST_PASSWORD }}
        port: ${{ secrets.APP_HOST_PORT }}
        strip_components: 1
        overwrite: true
        source: "src/compose.${{ inputs.environment }}.yml"
        target: /app
    - name: Deploy documentation files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.APP_HOST_SERVER }}
        username: ${{ secrets.APP_HOST_USERNAME }}
        password: ${{ secrets.APP_HOST_PASSWORD }}
        port: ${{ secrets.APP_HOST_PORT }}
        strip_components: 1
        overwrite: true
        source: "docs/**"
        target: /app/docs
