# Run terraform 
name: _TerraformSwarmTask

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      APP_ROOT_PASSWORD:
        required: true
      KAMATERA_API_KEY:
        required: true
      KAMATERA_API_SECRET:
        required: true
      TERRAFORM_API_SECRET:
        required: true

jobs:
  terraform:
    name: Terraform Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7          
      - name: Terraform Workspace
        run: terraform workspace select huybrechts-xyz-${{ inputs.environment }} || terraform workspace new huybrechts-xyz-${{ inputs.environment }}
      - name: Terraform Init
        run: terraform init
        working-directory: ./deploy
      - name: Terraform Plan
        env:
          APP_ROOT_PASSWORD: ${{ secrets.APP_ROOT_PASSWORD }}
          KAMATERA_API_KEY: ${{ secrets.KAMATERA_API_KEY }}
          KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}
          KAMATERA_ENVIRONMENT: ${{ inputs.environment }}
          TERRAFORM_API_SECRET: ${{ secrets.TERRAFORM_API_SECRET }}
        run: |
          echo "Setting up Kamatera credentials..."
          export TF_VAR_api_key=$KAMATERA_API_KEY
          export TF_VAR_api_secret=$KAMATERA_API_SECRET
          export TF_VAR_environment=$KAMATERA_ENVIRONMENT
          export TF_VAR_password=$APP_ROOT_PASSWORD
          export TF_TOKEN_app_terraform_io=$TERRAFORM_API_SECRET
          echo "Running terraform...PLAN"
          terraform plan -var-file="vars-${{ inputs.environment }}.tfvars" -input=false -out="plan.tfplan"
        working-directory: ./deploy
      - name: Terraform Apply
        env:
          APP_ROOT_PASSWORD: ${{ secrets.APP_ROOT_PASSWORD }}
          KAMATERA_API_KEY: ${{ secrets.KAMATERA_API_KEY }}
          KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}
          KAMATERA_ENVIRONMENT: ${{ inputs.environment }}
        run: |
          echo "Setting up Kamatera credentials..."
          export TF_VAR_api_key=$KAMATERA_API_KEY
          export TF_VAR_api_secret=$KAMATERA_API_SECRET
          export TF_VAR_environment=$KAMATERA_ENVIRONMENT
          export TF_VAR_password=$APP_ROOT_PASSWORD
          export TF_TOKEN_app_terraform_io=$TERRAFORM_API_SECRET
          echo "Running terraform...APPLY"
          terraform apply -auto-approve -var-file="vars-${{ inputs.environment }}.tfvars" -input=false
        working-directory: ./deploy
