# This reusable workflow Jobs
name: Reusable Build and Deploy Tasks

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      APP_HOST_SERVER:
        required: true
      APP_HOST_PORT:
        required: true
      APP_HOST_USERNAME:
        required: true
      APP_HOST_PASSWORD:
        required: true

jobs:
  deploy-stack-task:
    name: Deploy Docker Swarm Stack Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Update docker stack
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.APP_HOST_SERVER }}
          username: ${{ secrets.APP_HOST_USERNAME }}
          password: ${{ secrets.APP_HOST_PASSWORD }}
          port: ${{ secrets.APP_HOST_PORT }}
          script_stop: true
          script: |
            set -e
            cd /
            cd /app
            echo DOCKER DEPLOY
            sudo chmod -R 600 /app/cert
            sudo chmod -R 777 /app/data
            sudo chmod -R 777 /app/logs
            docker stack deploy -c compose.${{ inputs.environment }}.yml app &> /app/logs/deploy-stack.log