# Deploy Configuration Task
name: _DeployConfigurationTask

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      SERVER_ENDPOINT:
        required: true
      SERVER_PORT:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true

jobs:
  deploy-configuration:
    name: Deploy Configuration Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Deploy Generic Files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_ENDPOINT }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        strip_components: 1
        overwrite: true
        source: "src/*"
        target: "/app"
