# Deploy Docker Swarm Stack Task
name: Deploy Swarm Stack Task

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      SERVER_ENDPOINT:
        required: true
      SERVER_PORT:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true

jobs:
  deploy-stack:
    name: Deploy Swarm Stack Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Update docker stack
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_ENDPOINT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            set -e
            cd /
            # Set the application path
            cd /app
            # Set the appropriate security on the application subdirectories
            #echo APPY SECURITY
            sudo chmod -R 600 /app/traefik/data
            sudo chmod -R 777 /app/traefik/logs
            sudo chmod -R +x /app/scripts
            # Redeploy the new docker compose
            echo DOCKER DEPLOY
            docker stack deploy -c compose.${{ inputs.environment }}.yml --env-file ${{ inputs.environment }}.env app &> /app/deploy-stack.log
