# Deploy Docker Swarm Stack Task
name: _DeploySwarmTask

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      minio_data:
        required: true
        type: string
    secrets:
      APP_AUTH_GOOGLE:
        required: true
      APP_SMTP_OPTIONS:
        required: true
      SERVER_ENDPOINT:
        required: true
      SERVER_PORT:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_PASSWORD:
        required: true

jobs:
  deploy-stack:
    name: Deploy Swarm Stack Task
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Update docker stack
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_ENDPOINT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            set -e
            # Execute the previously uploaded script
            export ENVIRONMENT=${{ inputs.environment }}
            export MINIO_DATA=${{ inputs.minio_data }}
            /app/startenv.sh
