# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Website

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Staging

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build website
      run: dotnet build --no-restore
    - name: Test website
      run: dotnet test --no-build --verbosity normal
    - name: Build the Docker image
      run: docker build . --file src/website/Huybrechts.Web/Dockerfile --tag website:$(date +%s)

  publish:

    runs-on: ubuntu-latest
    environment: Staging

    steps:
    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the images to Docker Hub
      run: docker push huybrechts/website