# This workflow will build the Huybrecht.Web .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Production - Build Website

on:
  workflow_dispatch:
  
  #push:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

  #pull_request:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'
       
jobs:
  call-build-website:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_build-website.yml@main
    with:
      environment: Production
    secrets: inherit