# This workflow deploys all infrastructure to the shared environment
name: Deploy Infrastructure

on:
  workflow_dispatch:

  # push:
  #   branches: [ "main" ]
  #   paths: 
  #     - 'src/website/**'
  #     - '!src/website/*.yml'

jobs:
  deploy_infrastructure:
    name: Test Pipeline
    uses: ./.github/workflows/_pipeline.yml
    with:
      workspace: shared
      environment: test
      infrastructure: true
      rebuild: true
      services: ''
    secrets:
      BITWARDEN_TOKEN: ${{ secrets.BITWARDEN_TOKEN }}
