# This workflow deploys all shared services
name: Deploy Shared

on:
  workflow_dispatch:

jobs:
  deploy_shared:
    name: Deploy Shared
    uses: ./.github/workflows/_pipeline.yml
    with:
      workspace: platform
      environment: shared
      infrastructure: false
      rebuild: false
      appstack: ''
      services: ''
    secrets:
      BITWARDEN_TOKEN: ${{ secrets.BITWARDEN_TOKEN }}
