# This workflow deploys all components to the test environment
name: Deploy To Test

on:
  workflow_dispatch:

jobs:
  deploy_components:
    uses: _build-deploy.yml@main
    with:
      environment: test
      initialize: 'false'
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_DATA_TYPE: ${{ secrets.APP_DATA_TYPE }}
      APP_DATA_URL: ${{ secrets.APP_DATA_URL }}
      APP_DATA_NAME: ${{ secrets.APP_DATA_NAME }}
      APP_DATA_USERNAME: ${{ secrets.APP_DATA_USERNAME }}
      APP_DATA_PASSWORD: ${{ secrets.APP_DATA_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
