# This workflow deploys all components to the test environment
name: Deploy To Test (No Build)

on:
  workflow_dispatch:

jobs:
  deploy_components:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_pipeline.yml@main
    with:
      environment: test
      initialize: 'false'
      rebuild: 'false'
    secrets:
      APP_DATA_USERNAME: ${{ secrets.APP_DATA_USERNAME }}
      APP_DATA_PASSWORD: ${{ secrets.APP_DATA_PASSWORD }}
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
