# This workflow deploys the production environment

name: Deploy To Production

on:
  workflow_dispatch:

  #push:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

  #pull_request:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

jobs:
  deploy-traefik:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-image.yml@main
    with:
      environment: production
      component: traefik
    secrets: inherit
  
  deploy-whoami:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-image.yml@main
    with:
      environment: production
      component: whoami
    secrets: inherit