# This workflow will initialize a new server

name: Deploy Website

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

jobs:
  call-deploy-image:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-image.yml@main
    with:
      environment: Staging
      component: website
    secrets: inherit