# This workflow will initialize a new server

name: Deploy Traefik

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-image.yml@main
        with:
          environment: Staging
          component: traefik
        secrets: inherit
