# This workflow deploys all components to the staging environment
name: Deploy To Staging (Rebuild)

on:
  workflow_dispatch:

jobs:
  deploy_components:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_pipeline.yml@main
    with:
      environment: staging
      initialize: 'false'
      rebuild: 'false'
    secrets:
      APP_AUTH_GOOGLE: ${{ secrets.APP_AUTH_GOOGLE }}
      APP_DATA_NAME: ${{ secrets.APP_DATA_NAME }}
      APP_DATA_USERNAME: ${{ secrets.APP_DATA_USERNAME }}
      APP_DATA_PASSWORD: ${{ secrets.APP_DATA_PASSWORD }}
      APP_DATA_URL: ${{ secrets.APP_DATA_URL }}
      APP_HOST_EMAIL: ${{ secrets.APP_HOST_EMAIL }}
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_SMTP_OPTIONS: ${{ secrets.APP_SMTP_OPTIONS }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}