# This workflow will initialize a new server

name: Deploy Traefik

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

jobs:
  initialize:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v4
      - name: SSH Install Docker Compose
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          source: "src/traefik/docker-compose.traefik.yml"
          target: "/app/cfg/docker-compose.traefik.yml"