# This workflow deploys the development environment

name: Deploy To Development

on:
  workflow_dispatch:

  #push:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

  #pull_request:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

jobs:
  deploy-traefik:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-image.yml@main
    with:
      environment: development
      component: traefik
    secrets: inherit
  
  deploy-whoami:
      uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-image.yml@main
      with:
        environment: development
        component: whoami
      secrets: inherit