# This workflow deploys all components to the test environment
name: Deploy To Test

on:
  workflow_dispatch:

  # push:
  #   branches: [ "main" ]
  #   paths: 
  #     - 'src/website/**'
  #     - '!src/website/*.yml'

jobs:
  deploy_pipeline:
    name: Test Pipeline
    uses: ./.github/workflows/_pipeline.yml
    with:
      environment: test
      initialize: 'false'
      rebuild: 'false'
    secrets:
      BITWARDEN_TOKEN: ${{ secrets.BITWARDEN_TOKEN }}
