# This workflow deploys traefik to the development environment

name: Deploy Traefik To Development

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

jobs:
  deploy-component:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-component.yml@main
    with:
      environment: development
      component: traefik
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      APP_HOST_SERVER: ${{ secrets.HOST_APP_HOST_SERVERSERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}