# This workflow deploys the website to the development environment

name: Deploy Website Config To Development

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/website/*.yml'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/website/*.yml'

jobs:
  deploy-config:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: development
      component: whoami
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      
  deploy-stack:
    needs: [ deploy-config ]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-stack.yml@main
    with:
      environment: development
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}