# This workflow deploys traefik to the development environment

name: Deploy Consul To Development

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/consul/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/consul/**'

jobs:
  deploy-component:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-component.yml@main
    with:
      environment: development
      component: consul
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      
  deploy-stack:
    needs: [ deploy-component ]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-stack.yml@main
    with:
      environment: development
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}