# This workflow deploys whoami to the development environment

name: Deploy WhoAmI To Development

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/whoami/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/whoami/**'

jobs:
  deploy-component:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-component.yml@main
    with:
      environment: development
      component: whoami
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      APP_HOST_SERVER: ${{ secrets.HOST_APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}