# This workflow deploys all components to the production environment

name: Build and Deploy To Production

on:
  workflow_dispatch:

jobs:
  build-website:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_build-website.yml@main
    with:
      environment: production
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  deploy-traefik:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: production
      component: traefik
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  deploy-whoami:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: production
      component: whoami
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  deploy-website:
    needs: build-website
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: production
      component: website
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  deploy-postgres:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: production
      component: postgres
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  deploy-antora:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: production
      component: antora
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  deploy-stack:
    needs: [ deploy-traefik, deploy-website, deploy-whoami, deploy-postgres, deploy-antora ]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-stack.yml@main
    with:
      environment: production
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_EMAIL: ${{ secrets.APP_HOST_EMAIL }}
      APP_DATA_PROVIDER: ${{ secrets.APP_DATA_PROVIDER }}
      APP_DATA_URL: ${{ secrets.APP_DATA_URL }}
      APP_DATA_NAME: ${{ secrets.APP_DATA_NAME }}
      APP_DATA_USERNAME: ${{ secrets.APP_DATA_USERNAME }}
      APP_DATA_PASSWORD: ${{ secrets.APP_DATA_PASSWORD }}