# This workflow will initialize a new server

name: Production - Stack Deploy

on:
  workflow_dispatch:

  #push:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

  #pull_request:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

jobs:
  call-deploy-image:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_stack-deploy.yml@main
    with:
      environment: Production
    secrets: inherit