# This workflow will deploy the staging environment

name: Start Staging Environment

on:
  workflow_dispatch:

  #push:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

  #pull_request:
  #  branches: [ "main" ]
  #  paths: 
  #    - 'src/website/**'

jobs:
  start-docker-stack:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-stack.yml@main
    with:
      environment: staging
    secrets: inherit