# This workflow deploys all components to the test environment

name: Buid and Deploy To Test

on:
  workflow_dispatch:

jobs:
  build-website:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_build-website.yml@main
    with:
      environment: test
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  
  deploy-traefik:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: test
      component: traefik
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  deploy-whoami:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: test
      component: whoami
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
    
  deploy-website:
    needs: [ build-website ]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: test
      component: website
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  deploy-postgres:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: test
      component: postgres
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}

  # deploy-keycloak:
  #   uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
  #   with:
  #     environment: test
  #     component: keycloak
  #   secrets:
  #     APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
  #     APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
  #     APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
  #     APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
    
  deploy-stack:
    needs: [ deploy-traefik, deploy-website, deploy-whoami, deploy-postgres ] #, deploy-keycloak ]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-stack.yml@main
    with:
      environment: test
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_EMAIL: ${{ secrets.APP_HOST_EMAIL }}
      APP_DBASE_NAME: ${{ secrets.APP_DBASE_NAME }}