# This workflow deploys traefik to the test environment

name: Deploy Traefik To Test

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

  pull_request:
    branches: [ "main" ]
    paths: 
      - 'src/traefik/**'

jobs:
  deploy-config:
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-config.yml@main
    with:
      environment: test
      component: traefik
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      
  deploy-stack:
    needs: [ deploy-config ]
    uses: huybrechtsxyz/huybrechtsxyz/.github/workflows/_deploy-stack.yml@main
    with:
      environment: test
    secrets:
      APP_HOST_SERVER: ${{ secrets.APP_HOST_SERVER }}
      APP_HOST_USERNAME: ${{ secrets.APP_HOST_USERNAME }}
      APP_HOST_PASSWORD: ${{ secrets.APP_HOST_PASSWORD }}
      APP_HOST_PORT: ${{ secrets.APP_HOST_PORT }}
      APP_HOST_EMAIL: ${{ secrets.APP_HOST_EMAIL }}
      APP_DBASE_NAME: ${{ secrets.APP_DBASE_NAME }}